### PR TITLE
[1.20.x] Swapped codec of `EnvironmentScanPlacement` for `Direction` for less restrictions

### PR DESCRIPTION
**Pull request by DavidQF555**
Currently, the `EnvironmentScanPlacement` codec requires that the directions be vertical directions only. This is because the placement is mainly used for dripstone, which is only vertical. However, looking at the `EnvironmentScanPlacement.getPositions` method, there is no point in this restriction. This change would allow for any direction, which would allow developers to be more flexible with using this placement rather than needing to create a copy just to check horizontally. This change would also not break any existing mods because current mods would only use vertical directions.

### CODE REVIEW

**Comment by Technici4n** [comment]
Hi, can you update this PR to 1.20.2?

**Comment by DavidQF555** [comment]
> Hi, can you update this PR to 1.20.2?

These changes should update it to 1.20.2.

**Review by Technici4n — DISMISSED** [review]
OK this looks fine. Can you add a comment above the patch in case we have to port that code in the future? Something like
```java
// NeoForge: Allow any direction, not just vertical. The code already handles it fine.
```

**Comment by DavidQF555** [comment]
> OK this looks fine. Can you add a comment above the patch in case we have to port that code in the future? Something like
> 
> ```java
> // NeoForge: Allow any direction, not just vertical. The code already handles it fine.
> ```
Done.

**Review by Technici4n — APPROVED** [review]

**Comment by Technici4n** [comment]
Thanks!

**Pull request merged**
