### PR TITLE
Add Experimental FeatureFlag

### PR DESCRIPTION
**Pull request by ApexModder**
While I know modders should not be making custom FeatureFlags themselves I believe it would be handy if NeoForge itself provided some FeatureFlag modders could use to mark elements as being experimental.

- This FeatureFlag can be enabled like all the other experimental features, toggle it on during world creation from the Experiments Selection screen.
- Marking elements as requiring this FeatureFlag is done the same way as using the vanilla flags, set it during your elements registration (`requiredFeatures()` for Block/Item properties for example).

<details>

<summary>FeatureFlag selection</summary>

selection-screen

</details>

I have provided a simple test mod which register's a new Item and Block to the game, these are only enabled if the newly provided FeatureFlag is also enabled.

### CODE REVIEW

**Comment by Technici4n** [comment]
Why not use a config option in your mod to enable specific experimental features? A single feature flag is not granular enough.

**Comment by ApexModder** [comment]
Config option would _work_ but as there is currently no built-in config editor, unless you install a third party mod there is no way to toggle it in game.

Feature flags also fully disable the element, not just simply hide it from creative mode/give commands.

All item usages, block interactions, entity interactions etc are quit out early if its disabled via feature flag, unlike a config where its up to you, the modder to add all the necessary checks to quit out early everywhere when the config is disabled, which could easily lead to items in a weird semi enabled/disabled state due to forgetting some `if`.

**Comment by Technici4n** [comment]
Can't you just override `isEnabled(FeatureFlagSet)` in your item class?

Another issue is that feature flags are really inconvenient for mods because they cannot be changed once a world is created...

**Comment by ApexModder** [comment]
> Can't you just override isEnabled(FeatureFlagSet) in your item class?

yes'nt, you can override it but the system is not designed for it to change values on the fly (pull bool from a config).
Ive seen it result in weird psudeo enabled items where for example, if config is changed server side, item events fire client side but not server, as the enabled state is not synced with datapacks.

> Another issue is that feature flags are really inconvenient for mods because they cannot be changed once a world is created...

i mean i dont see this as an issue, its up to the user to enable the flag, its not enabled by default nor should it be. if a user chooses to enable the flag, they are given a warning that the world is being created with experimental settings, asking them if they want to go back and change it.

if the user enables it, thats a them problem imo, the game makes it very clear its about to enable them.

---

But if Neo is recommending we use configs for this, rather than modders reinventing the wheel in all their mods, Neo should provide some similar system to disable a registry object.

like a simple config on/off toggle bound to a holder, where when disabled does similar checks to isEnabled() to fully disable and hide the associated holder value from the game

**Comment by Technici4n** [comment]
>  Ive seen it result in weird psudeo enabled items where for example, if config is changed server side, item events fire client side but not server, as the enabled state is not synced with datapacks.

You can use server configs to avoid this exact issue.

This entire thing feels like trying to use a vanilla system for the sake of using a vanilla system, without really paying attention to what a mod is likely to need in practice. It is much more likely that server owners or mod pack developers want to disable a few specific items, than randomly enable a bunch of "mod experimental features", for example...

**Comment by ApexModder** [comment]
Then Neo imo should either extend FeatureFlags to allow more values/be toggled on the fly, or provide their own FeatureFlag-like system to toggle elements on the fly.

Why leave it upto every modder to implement in their own ways all with their own unique bugs. Mods should be able to assign a simple flag to their stuff to make them toggleable, and with this other mods could listen to this toggle and react based on its state (items auto-magicly hidding in recipe viewers if disabled).

The FeatureFlag system already provides all of this by simply setting the flag during registration, its only down sides is that they cant be toggled on the fly and are hard limited to 64 flags, crashing if a 65th is ever registered.

**Comment by XFactHD** [comment]
Extending the vanilla feature flag system is basically impossible. Allowing more than 64 flags is the comparatively trivial part since it would "only" involve replacing the use of `long`s used for storing and checking enabled flags with `BitSet`s (the patch surface would be fairly large though). The major issue is that the flag universe is created and set in stone before any mod starts loading, so actually registering new flags to the universe is simply not possible.

**Comment by Technici4n** [comment]
@XFactHD this PR adds a single new feature flag for "mod experimental features".

**Comment by XFactHD** [comment]
I'm referring to Apex's suggestion to have NeoForge extend the feature flag system to allow registration of arbitrary amounts of flags by mods

**Comment by ApexModder** [comment]
Yeah i wasnt expecting the vanilla system to be extended tbh, but providing our own similar system, where mods can bind elements to a flag and when the flag is toggled the associated values are hidden from the game, interactions dont fire, tickers dont register etc, would be good. and having other mods be able to listen to it for auto-magic jei item hiding and stuff would be neat too

Its just the vanilla flag system does all this already (if mods listen for isEnabled correctly, like they should be doing), and using the vanilla flags doesnt make sense for mods.
providing any flag is better than no flag, means mods can correctly disable experimental elements and encourages more mods to use isEnabled() where they currently are not.

**Comment by marchermans** [comment]
I personally do not see a reason for this change.
Any and all feature flags mods use, should simply use server configuration file. They are synced, modifiable even after the world has started, and can be created on the fly by any modder.

Is there a functional reason you want one global master flag?

**Comment by ApexModder** [comment]
I'm advocating for this merge because it introduces a built-in mechanism to label game elements as experimental or disabled, effectively disabling them. This includes:

- **Early termination** of all interaction/ticking methods, questioning the need to mark blocks/block entities as tickable and process ticks if they're "disabled".
- **Concealment** from creative tabs and recipe viewers.
- Provision of a **disabled tooltip** for players who somehow acquire them, informing them of their non-functionality.
- Ensuring parented/grouped elements are aware of their siblings' "enabled" state. For instance, block items check if the associated block is enabled, and spawn eggs check if the associated entity is enabled.

This flag could also raise awareness among modders about the `FeatureElement.isEnabled()` method, encouraging its adoption in their code and ensuring more mods are aware of whether a given element is enabled. While most commonly used mods correctly use this method, I've encountered some that disregard it and assume the element is always "enabled", which isn't always true.

The vanilla feature flag system offers all of the above. Ideally, modders could create their own flags for their specific uses. However, the current implementation of the vanilla system makes this impractical, leading to this PR's introduction of a single global flag. While not the best solution, it allows modders to utilize some of the built-in system.

Immediate responses from modders, such as "you shouldn't be using feature flags", can mislead people into thinking, "if I shouldn't be using feature flags, why check if it's enabled". It's important to note that you **should** be checking if a given element is enabled, even if modders can't currently use this system themselves.

If neoforge were to offer their own system allowing modders to label their elements as experimental/disabled, with all the benefits of the vanilla system, it would be preferable.

While overriding the method and using a config might work for items/blocks (despite some odd issues I've encountered), this can't be done for entities/menus as they directly take the field into the EntityType/MenuType, which modders shouldn't be custom implementing to override methods. This means modders can currently only mark items/blocks as experimental, not entities/menus.

---
**Footnote:** This comment was generated by an AI to articulate the points in a clear and concise manner.

**Comment by Technici4n** [comment]
A synced server config value should work. If you haven't tried it yet, please try it and explain why it doesn't work. That is the approach we are willing to support, potentially with more patches if required.

EDIT: My bad for not fully reading. The `requiredFeatures` in `EntityType` should easily be patchable to support a supplier or something like that. The other use cases are probably patchable too. We might want to deprecate `requiredFeatures`, and instead encourage people to check `isFeatureEnabled`.

**Comment by ApexModder** [comment]
[NeoForge | FeatureFlag ServerConfig Issue](https://www.youtube.com/watch?v=nSUYsdBohkA "NeoForge | FeatureFlag ServerConfig Issue")

When using server configs singleplayer works fine but servers seem to be failing to sync the config to clients leading to psudeo enabled/disabled items.

"psudeo enabled" - enabled and usable but commands can give and tool tip shows
"psudeo disabled" - disabled and unusable but commands can give and tool tip does not show

**Comment by Technici4n** [comment]
Is the value straight up incorrect on the client? Could it also be that server configs are synced too late?

**Comment by ApexModder** [comment]
I mean since nothing caches the result if `isEnabled()` it shouldnt rly matter when the server config is synced no? Everything just asks if `X is enabled` as and when its needed.
So long as the client config got synced and updated at some point, it should be fine?

as for if its wrong on the client, unsure how i would correctly test this but adding a breakpoint in `isEnabled()` breaks during the render thread and reports back as `false` when the config is set to `true`.

**Comment by ApexModder** [comment]
After some more experimentation and debugging ive realized that the issue with server configs, is due to the fact that they are only syncing the config value when client connects to the server.

Change the config file while your logged in, while the config hotswaps server side, it is not synced to the connected clients, leading to the interesting issues with config'd items. If the client does a quick relog the items enabled state is now synced and working as intended.

**Comment by ApexModder** [comment]
Closing due to PR going stale

**Pull request closed without merging**
