### PR TITLE
Move `LivingDamageEvent.Pre` call to be calculated before absorption.

### LINKED ISSUE #1267: Move `LivingDamageEvent.Pre` to be calculated before absorption
As discussed in discord: https://discord.com/channels/313125603924639766/1198800008225501285/1260054539084497027

It makes more sense to consider absorption as part of health, rather than a kind of damage reduction. Hence, it's better to move `LivingDamageEvent.Pre` calculation to be before absorption calculation.

Example:
I have a defensive gear that reduce damage by 50% and I want it to be implemented before magic and armor, because it could have some cost related to it. I takes 10 damage:
- If I have 10 absorption, current system will consume all 10 absorption, but it should consume 5 only.
- If I have 4 absorption, current system will deal me 3 damage, but it should deal me 1 damage only.

### PR DESCRIPTION
**Pull request by Spinoscythe**
it's better to move LivingDamageEvent.Pre calculation to be before absorption calculation, as we should consider absorption as an actual part of health.
Fixes #1267

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
@Caltinor does this look correct for the patching? Wanted eyes on it from a damage master

**Comment by Caltinor** [comment]
> @Caltinor does this look correct for the patching? Wanted eyes on it from a damage master

I would say no.  You wouldn't want the absorption to happen after the `onDamageTaken` hook.  Since that is provided the damage container for use in the callback, we want to give it the absorption reduction too.  Since it looks like there were no changes to the logic, only the sequence, I don't see why they didn't just move the `Pre` event to just before the absorption was calculated.

EDIT:  this also affected the outputs of the gametest.  @Spinoscythe you'll want to capture the absorption reduction value that was caught in `Pre` in the `Post` event so it can be checked by the gametest.

**Comment by Spinoscythe** [comment]
Will try to report on this ASAP. thanks for the feedback 🙏

**Comment by Spinoscythe** [comment]
I'm too busy for this now unfortunately, someone else can do it ;)

**Pull request closed without merging**
