### PR TITLE
Add back int cast on entity pathfinding

### LINKED ISSUE #647: Some entities' AI seems slightly broken (the entities move and spin)
**NeoForge Version:** 20.4.167

**Steps to Reproduce:**
 1. Load the world here: [Tets.zip](https://github.com/neoforged/NeoForge/files/14363882/Tets.zip)
 2. Take a hay bale
 3. Compare AI (path finding) behavior between NeoForge and Minecraft Vanilla

**Description of issue:**
(the entities move and spin on themselves)

NeoForge:

https://github.com/neoforged/NeoForge/assets/68275908/5139007e-8d86-4ca9-8188-e20c5b45481a

https://github.com/neoforged/NeoForge/assets/68275908/b44712fa-3bbb-4490-a9ab-6bed6bc40cd6

Vanilla:

https://github.com/neoforged/NeoForge/assets/68275908/86e593cb-d115-4034-96a3-06c11c60e4b1

### LINKED ISSUE #1274: [1.21] Rounding error causes pathfinding issues with certain entity sizes.
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.40-beta

**Logs:** N/A

**Steps to Reproduce:**
 1. Create an entity, with an entity type that is sized with a width of a `0.95F`.
 2. Mark debugging breakpoints in `PathNavigation#followThePath()` to log the values of `this.maxDistanceToWaypoint`, `d0`, and `d2`; see: https://github.com/neoforged/NeoForge/blob/e7daacf1334347b8a2c8078fb2b390ae6f06245b/patches/net/minecraft/world/entity/ai/navigation/PathNavigation.java.patch#L7-L13
 3. Observe values; `this.maxDistanceToWaypoint` will compute to 0.475, while `d0` and `d2` will compute to a similar value with a rounding error 0.4750000238418579.

**Description of issue:**
The patch for `PathNavigation#followThePath()` seems to cause a rounding error in specific circumstances dependent on an entity type's sizing, assumedly from conversions between float and double. The effects of this are that it can cause an entity to be at its targeted pathfinding node and yet the check for that will fail due to the rounding error, so the path never advances and the entity will stay stuck (although the entity seems to be able to get unstuck when interacted with by another entity). 

Changing the entity type sizing to a different value seems to work as a developer solution to this issue, but it's not an easy issue to pinpoint the cause of, so some might not even realize that's what's going on here.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
The original PR that solved the issue back in Forge: https://github.com/MinecraftForge/MinecraftForge/pull/6091
The second pathfinding issue: https://github.com/MinecraftForge/MinecraftForge/issues/7730

This PR closes: https://github.com/neoforged/NeoForge/issues/1274

@embeddedt was right the two fixes were required. The int casting and the equality check. In porting work, the int cast was lost. Oddly enough, the int cast was to fix an entity spinning issue while the equality check was to fix entity standing still forever when spawned until pushed. The lost of the int cast but the kept equal check didn't cause an entity spinning issue but the standing forever issue as reported in the Neoforge bug report.

Adding both fixes back resolves all issues. I tested by making Cows be 0.95 width and spawning them by spawn egg and watching them. The Cows were able to move on their own when spawned and did not exhibit any spinning behaviors.

After speaking with Wyn-Price, the original fix was based off of the casting seen in `Path#getVectorFromIndex` which is now called `Path#getEntityPosAtNode`. If the issue comes up again, please check this method for any Mojang changes and copy them into `PathNavigation#followThePath` and see if that fixes the issue.
image

### CODE REVIEW

**Comment by embeddedt** [comment]
Would like @bconlon1 to test the PR build once it finishes and confirm it resolves their original issue as well.

**Comment by TelepathicGrunt** [comment]
Closes https://github.com/neoforged/NeoForge/issues/647 as well

**Comment by shartte** [comment]
So, do we know **why** this works?
I am fine with saying "hey replicate Vanilla", since "position at path index" is a good enough analogue. 
We might want to comment in the path though, that it should match Vanillas implementation in `<insert method name here>`

**Comment by TelepathicGrunt** [comment]
@shartte The why is something I don't know specifically but my guess is vanilla is using both code paths for pathfinding and having one use the entity bounds as doubles while the other as ints is leading to an edge case where the entity position is mismatched? Specifically in `PathNavigation#tick` method. The `followThePath` is the method we patched. `getNextEntityPos` is the method that eventually calls `Path#getEntityPosAtNode`. So having the two see different positions due to casting probably is what is leading to spinning/freezing.

image

**Comment by shartte** [comment]
Oh I also meant: why is it adding 1 to the width of the entity when calculating the position?
It is essentially rounding up to the next block size and then computes the middle of that.

**Comment by TelepathicGrunt** [comment]
@shartte That + 1 is the vanilla code itself. It seems it is so that for entity bounds from [0, 1), the logic becomes basically xPos + 0.5. And when entity bounds is [1, 2), it is then xPos + 1. To me, looks like Path is doing a rough entity radius calc that is snapped to 0.5 increments?

For an absolute why it is done this way, only Mojang can answer probably

**Review by shartte — APPROVED** [review]

**Comment by bconlon1** [comment]
Will test when I can 👍

**Comment by bconlon1** [comment]
Managed to get the PR working to test, I can confirm this fixes the issue.

**Review by embeddedt — APPROVED** [review]

**Pull request merged**
