### PR TITLE
[1.20.5] Add data-driven brewing recipe system

### PR DESCRIPTION
**Pull request by Minecraftschurli**
This PR replaces the in code brewing recipe system added by neoforge on top of the hardcoded vanilla one with a data-driven approach through the recipe system

### CODE REVIEW

**Comment by KnightMiner** [comment]
This has been brought up many times before. The concerns usually raised are some combination of server with Neo on one side and vanilla the other will have desyncs if datapacks add anything. The notable case I remember is Neo server and vanilla client as the brewing slot filters are controlled by the brewing registry

**Comment by Minecraftschurli** [comment]
1. The vanilla checking has not been implemented yet but is easily possible
2. We have a discussion going in discord [here](https://discord.com/channels/313125603924639766/1191913413052473465)

**Review by Technici4n — COMMENTED** [review]
Personally I am not convinced, on behalf of this change being way too complicated.

**Comment by Shadows-of-Fire** [comment]
Given the recent changes to `PotionBrewing` in 1.20.5-pre1, we should dismiss this change and wait for vanilla to provide this functionality natively.

**Comment by TelepathicGrunt** [comment]
Do we want to close this PR and open a fresh one when 1.21.1 or later comes out? Mojang could make more changes

**Comment by Shadows-of-Fire** [comment]
Yeah, this isn't very feasible for us to do atm.  Closing.

**Pull request closed without merging**
