### PR TITLE
Provide support for Kotlin

### PR DESCRIPTION
**Pull request by Hantonik**
This PR provides native support for Kotlin and allows mods to use this language without external library mods.

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
Shipping Kotlin by default means we have to ship the Kotlin std libraries as part of Neo, which is not something we want to do.  We shipped Scala for a long time and it was a significant part of our total bandwidth usage.  The installer is currently ~5.5MB, and the Kotlin for Forge mod is ~7.5MB, so shipping it would more than double the installer size.

**Comment by Hantonik** [comment]
Actually the size of the installer has barely changed. It just downloads an extra ~4.9MB.

**Comment by gigaherz** [comment]
Because of the extreme load that downloading from the developer's websites causes (we received complaints from some CDNs in the past, if I recall correctly), it has always been a forge policy NOT to download files from anywhere other than the mojang servers and the forge servers.
Neo has the same policy, which means that if kotlin were to be added, the installer would request it from the neoforged maven, which means those 5mb would be an additional stress on **all** installs of neoforge, even if none of the mods people are actively using require kotlin.

**Comment by Hantonik** [comment]
If I understand correctly, you don't want to download kotlin libraries from external maven repositories, but kotlin is already on your servers. 

https://maven.neoforged.net/#/releases/org/jetbrains/kotlin

**Comment by ferriarnus** [comment]
Would it be an option to add this as an MDK template instead (if I read the changes right that's all that changed)? With regards to the external lib, I don't think it matters on which server it is, as it increases the load. Each mod could jij the file (which would increase the mod size instead), or a common lib mod could be used (as I think is now the case?)

**Comment by gigaherz** [comment]
What I meant is that since we **cannot** download from external servers, adding kotlin support would double the donwload bandwidth for neo, and by extension, the data transfer related server costs.
Adding kotlin to all instals by default is not a viable option, specially when language adapters are available on demand, and the majority of players use modpack managers with automatic dependency installation.

**Pull request closed without merging**
