### PR TITLE
Fixed download link leading to 404

### PR DESCRIPTION
**Pull request by Speiger**

### CODE REVIEW

**Comment by Speiger** [comment]
Small note, i dunno why the "curseforge placeholder" was also marked as changed...

**Comment by Technici4n** [comment]
Probably a line ending change? (LF vs CRLF?)

**Comment by Speiger** [comment]
@Technici4n but i didn't even edit that line O.o And i used githubs online editor xD

**Comment by Technici4n** [comment]
Yeah it added a newline: https://github.com/neoforged/NeoForge/pull/147.diff

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
