### PR TITLE
[FIX] Don't attempt to format modinfo localizations

### PR DESCRIPTION
**Pull request by MattSturgeon**
A user [reported on discord](https://discord.com/channels/313125603924639766/1116211620415283201/1214183862133850153) that their mod caused "Illegal format found" errors to be spammed in the log caused by their mod's display name including `'` chars.

```
[ne.ne.ne.co.I18nExtension/CORE]: Illegal format found `Armourer's Workshop`
```

This fixes those errors by not attempting to parse modinfo as a format string in `I18nExtension`.

### CODE REVIEW

**Comment by MattSturgeon** [comment]
Does this warrant additional tests? If so, are there any good examples for how Neoforge usually tests this kinda thing?

**Comment by Drullkus** [comment]
Are there any possibility for this PR to be accepted?

**Comment by Technici4n** [comment]
We need to revert the ability to translate mod names IMO. Hasn't happened yet.

**Comment by MattSturgeon** [comment]
> We need to revert the ability to translate mod names IMO

I don't see why that blocks this PR.

1. This PR fixes both mod names **and** descriptions
2. The names fix will be useful until translatable names are removed
3. This doesn't make it any harder to remove translatable names

**Comment by Technici4n** [comment]
Now that https://github.com/neoforged/NeoForge/pull/851 went in for 1.20.5 I'm happy to merge this.

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
