### PR TITLE
Add warning for wrong mob category in biomes

### LINKED ISSUE #1250: Add log warning if a mob is added to wrong mob category in biomes
Came up in: https://github.com/neoforged/NeoForge/pull/689#pullrequestreview-2161871841

Right now, if a mob is added to the wrong mob cap, that mob could spawn uncontrollably without ever stopping. Or its spawns are inconsistent. Vanilla actually has this bug with ocelots.
https://bugs.mojang.com/browse/MC-1788

Perhaps Neo can patch vanilla json to put Ocelots in the right mob category in the Jungle biomes. And then add a check to log if it detects any mob in wrong category so modders know. It can even state which category it expects the mob under.

Note, we have to consider enum extended mob categories too

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Example of the message output that will occur on every world load after Biome Modifiers are applied:
```
[08:48:00] [Server thread/WARN] [ne.ne.ne.se.ServerLifecycleHooks/]: Detected entity.minecraft.cow added under MONSTER mob category for minecraft:bamboo_jungle biome! Mobs should be added to biomes under the same mob category that the mob was registered as to prevent mob cap spawning issues.
[08:48:00] [Server thread/WARN] [ne.ne.ne.se.ServerLifecycleHooks/]: Detected entity.minecraft.cow added under MONSTER mob category for minecraft:jungle biome! Mobs should be added to biomes under the same mob category that the mob was registered as to prevent mob cap spawning issues.
```

The vanilla bug https://bugs.mojang.com/browse/MC-1788 is special cased to not log at all.

Closes https://github.com/neoforged/NeoForge/issues/1250

### CODE REVIEW

**Review by XFactHD — CHANGES_REQUESTED** [review]
I would prefer a message that includes both the category an entity was registered under and the category it has in the spawn data, i.e. something along the lines of `Entity {} was added to biome {} under mob category {} but registered under mob category {}! ...`.

The entity types should ideally also use `BuiltInRegistries.ENTITY_TYPE.getKey()` instead of `EntityType#toString()` as the latter is the translation key, which isn't really suitable for this kind of thing.

**Comment by TelepathicGrunt** [comment]
@XFactHD fixed now:
```
[17:06:34] [Server thread/WARN] [ne.ne.ne.se.ServerLifecycleHooks/]: Detected minecraft:ocelot that was registered with CREATURE mob category but was added under MONSTER mob category for minecraft:bamboo_jungle biome! This is a vanilla bug. See https://bugs.mojang.com/browse/MC-1788 for more details.
[17:06:34] [Server thread/WARN] [ne.ne.ne.se.ServerLifecycleHooks/]: Detected minecraft:ocelot that was registered with CREATURE mob category but was added under MONSTER mob category for minecraft:jungle biome! This is a vanilla bug. See https://bugs.mojang.com/browse/MC-1788 for more details.
```

**Review by XFactHD — DISMISSED** [review]

**Comment by marchermans** [comment]
IMHO I don't think we should log at all for entities within the minecraft namespace.

**Comment by TelepathicGrunt** [comment]
@marchermans counterpoint. Mods can add to vanilla biomes in wrong category. Or put vanilla mobs in the wrong category in modded biomes. Not logging vanilla mobs or biome would be such a glaring oversight that this entire logging would be pointless

**Comment by TelepathicGrunt** [comment]
PR updated to not log for the specific ocelot vanilla bug

**Review by XFactHD — APPROVED** [review]

**Review by embeddedt — APPROVED** [review]

**Pull request merged**
