### PR TITLE
Unbreak the MC-176559 fix

### LINKED ISSUE #143: MC-176559 fix (`IForgeItem#shouldCauseBlockBreakReset`) doesn't work
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.65

**Logs:** Not needed

**Steps to Reproduce:**
 1. Create a new item that repairs it overtime within `inventoryTick`
 2. The mining animation resets if the stack heals during mining

**Description of issue:**
The fix made to MC-176559 (mending resets mining progress / breaking animation) doesn't work as in `MultiPlayerGameMode#sameDestroyTarget` the game still checks if the stacks match with tag (`ItemStack.isSameItemSameTags`), making the` IForgeItem#shouldCauseBlockBreakReset` check useless.

```java
   private boolean sameDestroyTarget(BlockPos pPos) {
      ItemStack itemstack = this.minecraft.player.getMainHandItem();
      return pPos.equals(this.destroyBlockPos) && ItemStack.isSameItemSameTags(itemstack, this.destroyingItem) && !destroyingItem.shouldCauseBlockBreakReset(itemstack);
   }
```

### PR DESCRIPTION
**Pull request by Tkain**
NeoForge tries to fix [MC-176559](https://bugs.mojang.com/browse/MC-176559) by including its own logic to determine whether block breaking should be interrupted when an item changes (ex. is swapped or is healed with mending). However, because this logic is AND-ed with vanilla's check that the item has the same tags before and after the change, NeoForge's own logic only runs when both items already have the same tags. This breaks NeoForge's fix for MC-176559, which would otherwise prevent block breaking from being interrupted when only an item's durability changes.

To fix this, we simply remove vanilla's `isSameItemSameTags()` call before we call NeoForge's `shouldCauseBlockBreakReset()`; the latter calls the former in appropriate scenarios anyway.

Resolves #143.

### CODE REVIEW

**Review by ChampionAsh5357 — DISMISSED** [review]
The solution looks fine since the method in question is called within the forge extension. Triage can test and validate ~~while my computer is being a hot brick~~

**Review by Technici4n — DISMISSED** [review]

**Comment by Technici4n** [comment]
Hi, can you update this PR to 1.20.2?

**Comment by KingLemming** [comment]
Is there a reason this can't be considered for 1.20.1? Just curious.

**Comment by Technici4n** [comment]
The usual policy is to always merge for the latest version first, to ensure that no commit is accepted on 1.20.1 and forgotten in 1.20.2.

**Comment by KingLemming** [comment]
It seems the better request would be to ask for a simultaneous PR to 1.20.2 then and not a refactor of this one, with a hopeful backport.

**Review by sciwhiz12 — APPROVED** [review]

**Pull request merged**
