### PR TITLE
[1.20.4] Select Music Event

### PR DESCRIPTION
**Pull request by Zepalesque**
See #862, this is the same, just backported to 1.20.4

### CODE REVIEW

**Comment by Zepalesque** [comment]
still need to make the newer changes to this

**Comment by TelepathicGrunt** [comment]
@Zepalesque Are you still working on this PR or should it be closed? Not sure if people are sticking around in 1.20.4 at all at this point

**Comment by Zepalesque** [comment]
yeah I am still planning on backporting it at _some_ point, just haven't gotten around to it yet

**Comment by Shadows-of-Fire** [comment]
Closing due to lack of development; if you ever get around to updating it, you can reopen this or a new PR for the same change.

**Pull request closed without merging**
