### PR TITLE
Fire Villager/Wandering Trader trade events on /reload

### LINKED ISSUE #721: Re-fire villager/wandering trader trade events during /reload
Currently both of these events are only fired during the `ServerAboutToStartEvent`, which means that reflecting changes to them requires restarting the server.

I believe these events should be capable of being fired during resource reload instead, allowing for trades to be recomputed on `/reload`.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Fixes https://github.com/neoforged/NeoForge/issues/721

Fired on tag updated event to make sure all tags are ready for use in case modders are using tags in their trade events.

### CODE REVIEW

**Comment by Matyrobbrt** [comment]
The `TagsUpdatedEvent` is fired on both sides, unlike server starting. Are the trade events being fired therefore on both sides intentional, or should it only be fired on the server?

**Comment by TelepathicGrunt** [comment]
The old code fired during server about to start so it seems this should be serversided. I did not know the tags updated event fired on both sides hmm

**Comment by XFactHD** [comment]
`TagsUpdatedEvent` has an update cause which indicates whether it fires from reload on the server or sync on the client which you can check.

**Comment by TelepathicGrunt** [comment]
Tested now with the datapack sync check. On client and server, it fires only once when world is started up. And fires once per /reload. Looks good now!

**Comment by Shadows-of-Fire** [comment]
Event javadocs need to be updated to reflect the fact that they now fire on reload instead of once during the `ServerAboutToStartEvent`.

**Review by Shadows-of-Fire — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Pull request merged**
