### PR TITLE
Use new logo in README

### PR DESCRIPTION
**Pull request by PlatinPython**
Replace the old docs/assets/neoforged_logo.png with the new logo and remove the leftover, unused assets.

### CODE REVIEW

**Comment by PlatinPython** [comment]
Updated the texture to use the fixed one from #90.

**Comment by pupnewfster** [comment]
Rather than having to keep it synced up is there a reason we can't just have it reference and pull the `docs/assets/installer.png` logo for which one it embeds? Rather than having two "identical" image files in the `docs/assets` folder but with different names.

**Comment by PlatinPython** [comment]
I personally have no problems with doing that. I'm just not a huge fan of referencing a file called `installer.png` in the README so I'd advocate for the installer to use `neoforged_logo.png` instead.

**Comment by pupnewfster** [comment]
Sounds reasonable, and I believe it would just require a [one line change to the build.gradle](https://github.com/neoforged/NeoForge/blob/016a46c27a3b4a70364887cf114653cb8a3b825b/build.gradle#L1249) to make it use the different file in the installer

**Review by AterAnimAvis — APPROVED** [review]

**Pull request merged**
