### PR TITLE
Add splash manager and splash registration event

### PR DESCRIPTION
**Pull request by FiniteReality**
This is a work in progress, in order to gauge interest in managing splashes centrally in NeoForge.

It's often the case that modders would like to add custom splashes to the title screen, except that doing so generally means using a mixin, or completely overwriting the splash pool with a custom resource pack. In order to alleviate that, I've started working on a system to overhaul the vanilla splash manager in such a way that mods can add their own splashes without conflicts. This implementation isn't complete, and it's missing tests, but some preliminary testing does indeed show that it works:
<details>
<summary>Screenshots of custom splashes and date/time specific splashes</summary>

Screenshot_20240117_232614
Screenshot_20240117_232216
</details>

If there's interest in a system like this, there are some open questions I have:
- Should this system be data-driven?
  - If so, how should it be structured?
    - A single `assets/modid/splashes.json`?
    - A directory of json files, a la `assets/modid/splashes/christmas.json`?
  - Should it use `neoforge:conditions`, or dispatch on some sort of `type` field, like recipes?
  - How do we handle backwards-compatibility with the vanilla format?
- How should we handle ordering between mods and vanilla?
  - If ModA and ModB both add a date/time-specific entry which overlap, which one do we pick?

There's likely way more questions that need to be answered, but I can't think of anything obvious right now :sweat_smile:

### CODE REVIEW

**Review by marchermans — APPROVED** [review]

**Review by Technici4n — COMMENTED** [review]
I would prefer a simple resource pack-based system, maybe a file with extra splashes, or an extra marker line at the top of splashes.txt to not override previous entries. Of course, we need to preserve the ability for pack makers to override the full set of splashes, but they might be able to easily do that with pack overlays already.

**Comment by FiniteReality** [comment]
> I would prefer a simple resource pack-based system, maybe a file with extra splashes, or an extra marker line at the top of splashes.txt to not override previous entries.

This would work for the random splash pool, but for date/time based splashes like the Christmas splash we would need a more complex solution. I do agree that a data-driven system would likely be ideal in the long run, however

> Of course, we need to preserve the ability for pack makers to override the full set of splashes, but they might be able to easily do that with pack overlays already.

As it stands right now, my understanding is that any pack providing a `texts/splashes.txt` will override the random splash pool completely.

**Comment by PlatinPython** [comment]
For date/time based splashes, choosing one at random is probably easiest/fairest. I personally don't see any reason a certain halloween/christmas/new year/whatever splash should be preferred over a different one.

**Comment by Technici4n** [comment]
I don't really care about time based splashes tbh... Do we expect modders to do? It's quite the niche hook

**Comment by TelepathicGrunt** [comment]
How about having the splash text be done similar to how biome modifiers work? An additions phase for adding splash text and a removal phase afterwards to remove specific splash text. It could be a file that specifies addition phase and provides a list of splash text to add. Maybe with a conditions field that is true by default. From there, a modder could implement a custom condition to only apply certain days of the year

**Comment by HenryLoenwind** [comment]
Custom conditions sounds good. I would add splashes that promote using mod features and others that congratulate on doing so, then keep track of the player using those features to disable the promotes and enable the congrats.

**Comment by TelepathicGrunt** [comment]
@FiniteReality Are you still looking to work on this PR or is this going to be shelved for now?

**Comment by FiniteReality** [comment]
> @FiniteReality Are you still looking to work on this PR or is this going to be shelved for now?

There's only mild support for it, and no people jumpiung out and saying they'll use it, so I think I'll shelve it for now.

**Pull request closed without merging**
