### PR TITLE
[1.20.1] Pull `ProjectileHitEvent` changes from MCF/1.20.x

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
This PR is a subset of #14 which pulls only the changes from https://github.com/MinecraftForge/MinecraftForge/pull/9642

### CODE REVIEW

**Comment by TheCurle** [comment]
This seems useful to have. We should try to port this one forward.

**Comment by jsburger** [comment]
I ran into an issue with this change while on Forge. I used the event to bounce projectiles off of certain blocks. I would cancel the event and change the projectile's motion. The new options are fine, the problem is that there is no option to do nothing on impact. Every impact result leads to the arrow landing in the block or being discarded.

**Comment by Shadows-of-Fire** [comment]
Sounds like we may need to add an `IGNORE` impact result which allows moving/redirecting the arrow without committing the impact.

**Comment by sciwhiz12** [comment]
Closing for now since it's approximately 1 year since this PR was opened and it seems it's not moving forward anytime soon.

Feel free to reopen the PR or make a new one as needed.

**Pull request closed without merging**
