### PR TITLE
Fire LivingConversionEvent Pre and Post properly for Husk, Tadpole, Mushroom, and Skeleton conversions

### LINKED ISSUE #505: Oversights with `LivingConversionEvent`
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.77

**Description of issue:**
1. `LivingConversionEvent.Pre` nor `LivingConversionEvent.Post` do not fire for skeletons converting to strays in powder snow. This case seems to have simply been missed when the event was introduced.
2. `LivingConversionEvent.Pre` wrongly reports submerged husks converting to drowneds when they actually convert to zombies, that then convert to drowneds in a separate process. This is caused by husks inheriting the event invocation from the zombie superclass.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Fixes https://github.com/neoforged/NeoForge/issues/505

Husks turn into Zombies when they drown once. Then after some time, the Zombie drowns into Drowned. The conversion is not Husk to Drowned. It's Husk -> Zombie -> Drowned.

Added patch to fire pre and post for Skeleton turning into Strays in Powder Snow

Handles Tadpole to growing up into Frogs

And handles Mooshroom sheared into Cows too

### CODE REVIEW

**Review by TheCurle — DISMISSED** [review]

**Comment by TheCurle** [comment]
I like how this conversion chain implies that the water in Minecraft is innately magical. Gives me an idea for a mod feature...

**Review by embeddedt — DISMISSED** [review]

**Comment by Fuzss** [comment]
Just saw Fabric Api added this event in the latest version, and theirs also fires for tadpoles growing up into frogs (in `Tadpole::ageUp`). That's the only mob in vanilla that is replaced with another mob on growing up.

Maybe this case can be added with the PR as well?

**Comment by TelepathicGrunt** [comment]
@Fuzss Adding that. Is there any other cases where entity type transforms into a different entity type not covered by this event?

Cases:

- Husk -> Zombie (This PR)
- Skeleton -> Stray (This PR)
- Tadpole -> Frog (This PR)
- Zombie -> Drowned (already handled)
- Zombie Villager -> Villager (already handled)
- Villager -> Witch (already handled)
- Pig -> Zombified Piglin (already handled)
- Piglin -> Zombified Piglin (already handled)
- Hoglin -> Zoglin (already handled)

**Comment by Fuzss** [comment]
Just did a quick search by looking at invocations of `Entity::setCustomName` since that's usually a good indicator to find when entity data is being copied. Looking at this mainly from the viewpoint of attachments since they use `LivingConversionEvent .Post`, so if something like the entity name is copied over attachments probably should be, too.

Two more cases I found:
- Mushroom turning into a cow when shearing in `MushroomCow::shear` (vanilla copies health, name, position, rotation, persistence, invulnerability)
- Slimes splitting into smaller slimes in `Slime::remove` (vanilla copies persistence, invulnerability, no ai, name)

**Comment by TelepathicGrunt** [comment]
The mooshroom -> cow was missed yeah. I'll get that

The slime splitting doesn't really change entity types so I dont think they fit this conversion event imo.

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
