### PR TITLE
[1.20.4] Adjust registration order of modded registry entries to follow BuiltInRegistries.LOADERS

### PR DESCRIPTION
**Pull request by XFactHD**
This PR changes the order in which registration is run for modded entries to match the order of the `BuiltInRegistries.LOADERS` map instead of the captured order in which the first registration to each vanilla registry happens due to static init of vanilla's registry entries. This allows the removal of additional supplier patches, one example of which is the `MobBucketItem` (`EntityType`s are incorrectly being registered after `Item`s).

This is required for additional supplier patch removals in #520

### CODE REVIEW

**Review by embeddedt — DISMISSED** [review]
Code looks reasonable to me.

**Review by embeddedt — APPROVED** [review]

**Comment by pupnewfster** [comment]
Just to confirm as I haven’t looked at it on my computer yet, but do custom registries still work properly with this change? I forget if they got included by the tracking known registries and I haven’t looked how loaders is populated.

**Review by Technici4n — COMMENTED** [review]
The generated order is quite useless IMO

**Comment by XFactHD** [comment]
> Just to confirm as I haven’t looked at it on my computer yet, but do custom registries still work properly with this change? I forget if they got included by the tracking known registries and I haven’t looked how loaders is populated.

Neither the tracking of known registries (which this PR removes anyway) nor the loaders map is relevant to custom registries, though the known registries map did of course capture modded registries once the registry events fired for them. Right before registry events are fired, the vanilla registries in the desired registration order (previously the captured one, now the one from the key set of the loaders map) is copied to a new set and then all registered registries (which includes modded ones) are added to that set in order as sorted by `ResourceLocation#compareNamespaced()`.
I ran all Neo gametests over this and tested it in a mod dev environment where I use a custom registry and both worked fine.

> The generated order is quite useless IMO

I'm gonna leave that up to maty and Commoble since they both suggested the inclusion of such a generated file.

**Comment by Technici4n** [comment]
IMO including such a file only makes sense if the order is different from what one might expect. I'd suggest documenting in the `RegisterEvent` that the vanilla registries follow the order in `BuiltInRegistries`.

**Comment by TheCurle** [comment]
Personal opinion: having this file is nice future proofing, and shows us visually when something changes the order of registries via a diff in that file. It may be possible to miss an accidental change without this, so I like the idea of having it.

**Comment by Technici4n** [comment]
Yeah that's a good point Curle

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
