### PR TITLE
Remove useless patched in blockEntity checks

### LINKED ISSUE #378: Patch to blockentity removal on blockstate change doesn't function as intended
Vanilla removes blockentities on blockstate removal in two relevant places: 

BlockBehaviour#onRemove removes the blockentity if the old blockstate has a blockentity and the block changes.
https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/level/block/state/BlockBehaviour.java.patch#L23C1-L29C7

We patch this this slightly; the intent is that if the old state had a blockentity and the new state doesn't, but are states of the same block, we should still remove the blockentity.

```diff
     @Deprecated
     public void onRemove(BlockState p_60515_, Level p_60516_, BlockPos p_60517_, BlockState p_60518_, boolean p_60519_) {
-        if (p_60515_.hasBlockEntity() && !p_60515_.is(p_60518_.getBlock())) {
+        if (p_60515_.hasBlockEntity() && (!p_60515_.is(p_60518_.getBlock()) || !p_60518_.hasBlockEntity())) {
             p_60516_.removeBlockEntity(p_60517_);
         }
     }
```

LevelChunk#setBlockState has an identical check, which is only done on the client thread:
https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/level/chunk/LevelChunk.java.patch#L13C1-L19C19
```diff
                 boolean flag2 = blockstate.hasBlockEntity();
                 if (!this.level.isClientSide) {
                     blockstate.onRemove(this.level, p_62865_, p_62866_, p_62867_);
-                } else if (!blockstate.is(block) && flag2) {
+                } else if ((!blockstate.is(block) || !p_62866_.hasBlockEntity()) && flag2) {
                     this.removeBlockEntity(p_62865_);
                 }
```

This is all well and good, except we use `state.hasBlockEntity()` to check whether a state has a blockentity or not. Observe this method:

```java
        public boolean hasBlockEntity() {
            return this.getBlock() instanceof EntityBlock;
        }
```

This method will always return the same value for every state of a given block, so the concept of one of a block's state having a blockentity and another of that block's states not having a blockentity isn't actually a thing at the moment, and the patches as they currently exist have identical behavior to the vanilla code (they're likely leftovers from the pre-EntityBlock era).

We should do one of two things:
A) Go along with the mojang logic and declare that either all the states of a block must have blockentities, or none of them do, and remove the two patches to reduce patch surface and confusion (this is the trivial solution)
B) reintroduce IBlockExtension#hasBlockEntity(BlockState) and patch BlockStateBase#hasBlockEntity to check that (this may cause unforseen consequences elsewhere as it breaks the mojang assumption that hasBlockEntity() doesn't differ between a block's states)

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Simply put, we have a hasBlockEntity method in the BlockState that takes no params. So modders cannot make a block have some states with a block entity and some states without. If they try, then hasBlockEntity is going to be wrong for several states.

Knowing that the method cannot support per-blockstate BlockEntity status, these two patches we have been doing are thus, useless and doesn't do anything. They were originally intended for removing a block entity if switching from a state with a blockEntity to a state without a blockEntity while still being the same block. And our check thus, was not actually checking for this condition. 

Changing hasBlockEntity to take a blockstate could have side-effects that we do not like. Seems safer to remove the checks instead

Closes https://github.com/neoforged/NeoForge/issues/378

### CODE REVIEW

**Review by embeddedt — APPROVED** [review]

**Comment by KnightMiner** [comment]
This is not accurate, I have per block state block entities on 1.19.2 working just fine, so unless it changed recently I am making use of this feature.

Looking at the patch, I am not sure that this specific call to the state sensitive block entity check method is what I use, but I know its something that was possible in Neo before. Its worth asking someone who has state sensitive block entities on 1.21 what they are currently doing to make it possible.

----

If the problem is simply no method on block exists that receives the `BlockState` parameter, then lets add one to make my implementation of state sensitive blockstates easier.

**Comment by TelepathicGrunt** [comment]
@KnightMiner hasBlockEntity is a mojang method. And is heavily used throughout the game (31 checks) with the assumption that a block does not have both block entity states and non-block entity states. I suspect your use case, even back in 1.19.2, is broken in several situations that you haven't experienced yet. 
image

Patching all these calls to do a blockstate check instead seems excessive. Technically we could convert 
```
public boolean hasBlockEntity() {
    return this.getBlock() instanceof EntityBlock;
}
```
to be
```
public boolean hasBlockEntity() {
    return hasBlockEntity(this);
}

public boolean hasBlockEntity(BlockState state) {
    return this.getBlock().hasBlockEntity(state);
}
```

Could work but then we need to go through all the vanilla usages and verify for sure that mojang did not leave a pitfall somewhere where doing this could cause issues

Are you absolutely positive that your use case can only be supported by have a single block have states that can both be with a block entity and not? Splitting them into a block without block entity and a block with block entity seems both more logical, expected, and cleaner imo.

**Comment by KnightMiner** [comment]
My usecase becomes a ton more complex if I remove the conditional block state. Both with and without the block state have the same item form, the same model, etc. along with several usages of tags that start to break down when I suddenly have a form of the block that is valid in my structure but only when it is not that ID. The block entity is just a conditional data holder that is left out, I should not be required to duplicate all my registrations for something that was previously supported. I am hardly the only one who has attempted this; I was given advice of how to achieve this from another modder doing the same thing.

My point is I am hardly a unique case here. Sure, I could refactor to not do conditional block states, but thats a lot of effort to move away from something that works fine. As for "there are probably cases you just have not noticed", I doubt it or I'd have issue reports by now; I tested it extensively and saw no issues back on 1.19.2.

----

All that said, I am not sure whether these patches had any impact on my implementation; its been too long since I looked at the code. Your comment that this was impossible though stood out as I have demonstrative proof that its not impossible, so this PR needs more consideration before it is merged.

Vanilla has a surprising amount of methods that suggest state sensitive block entities should be supported, its just that one odd case where `BlockState::hasBlockEntity` is hardcoded to not allow being conditional via state.

**Comment by embeddedt** [comment]
@KnightMiner Please provide a code example of how one can create a per-blockstate BE; I do not see how it can be possible in 1.18/1.19, unless you are patching the game yourself to reintroduce it. It seems more likely the BE is still created but maybe doesn't tick or something.

**Comment by HenryLoenwind** [comment]
KnightMiner, I'm pretty sure the changes in this PR have no impact on your code.

`if (p_60515_.hasBlockEntity() && (!p_60515_.is(p_60518_.getBlock()) || !p_60518_.hasBlockEntity())) {`

These two hasBlockEntity() will always return the same value for all blockstates of the same block, the middle check makes sure those blockstates are for the same block, so when p_60515_.hasBlockEntity() returns, and is() returns true, which allows the second hasBlockEntity() to run, it's result always will be true and a no-op.

Possible cases:

- true && (!true || !true) => false
- true && (!false || not evaluated) => true
- false && not evaluated => false

Which means the second hasBlockEntity() is pointless and has not effect on the outcome.

---

It's the same for the second one:

`} else if ((!blockstate.is(p_62866_.getBlock()) || !p_62866_.hasBlockEntity()) && blockstate.hasBlockEntity()) {`

(I inlined block and flag2 for clarity).

- !true || !true && !true
- !true || !false && not evaluated
- !false || not evaluated

Again, the extra hasBlockEntity() has no effect on the outcome of that if statement.

**Comment by TelepathicGrunt** [comment]
@KnightMiner  Just FYI, there are bugs that are highly likely to exist in 1.19.2 if doing per-blockstate BlockEntities due to this vanilla `hasBlockEntity` method (where you return true for `hasBlockEntity`). The bugs I see are:

- Non-BlockEntity BlockStates are not pushable by pistons

- In commands that take a block tag, BlockStateParser is going to assume the default BlockState of the block has a BlockEntity. And then will suggest `{` for nbt in a command for the block even if your default BlockState does not have a BlockEntity.

- WorldGenRegion#setBlock during the phase that is not `ChunkType.LEVELCHUNK` will create a CompoundTag with x, y, z, and "DUMMY" id to save at the spot even if the BlockState does not have a BlockEntity because `hasBlockEntity` returned true. This then causes ChunkAccess#getBlockEntitiesPos to report your block's position as a BlockEntity.

- LevelChunk#setBlockState would not remove the BlockEntity when switching from a BlockState with one to a BlockState without the BlockEntity when it is the same block each time. The patch here literally did nothing so this issue would exist in 1.19.2 anyway.

- LevelChunk#createBlockEntity looks like it will call `newBlockEntity` on your BlockState without a BlockEntity to try and force create the BlockEntity. You would have to know this before-hand and return null when the state isn't what you want.

- LevelChunk#getBlockEntity which calls LevelChunk#promotePendingBlockEntity looks like it will spam `Tried to load a block entity for block {} but failed at location {}` if a BlockState without the BlockEntity was placed during worldgen. It checks if "DUMMY" id exist for CompoundTag and if so, will call `newBlockEntity` on your BlockState without a BlockEntity to try and force create the BlockEntity. If you return null from this method, then the logspam will occur.

- BlockBehavior#onRemove would not remove the BlockEntity when switching from a BlockState with one to a BlockState without the BlockEntity when it is the same block each time. The patch here literally did nothing so this issue would exist in 1.19.2 anyway.

Luckily, rest of `hasBlockEntity` calls are paired with `getBlockEntity` call which returns null for non-BlockEntity BlockStates which usually would trigger the false `hasBlockEntity` codepath so those areas aren't actually breaking.

But overall, looks like you missed several side-effects in forcing the game to take you per-BlockState BlockEntities. Assuming that your BlockState are actually per-state BlockEntities and not just empty BlockEntities for your "non-BE" states. Which mod is this in 1.19.2 and how do we get a "non-BE" state in your mod? I would be curious to see if data command shows a hint of a BE actually existing or we can make a small mod to check if BE is at spot.

**Comment by KnightMiner** [comment]
> Non-BlockEntity BlockStates are not pushable by pistons

there are so many issues that open up if my block is pusable by pistons anyways, I'd have disabled it even if it worked. Though a Neo patch adding conditional `hasBlockEntity` would easily solve this.

> In commands that take a block tag, BlockStateParser is going to assume the default BlockState of the block has a BlockEntity. And then will suggest { for nbt in a command for the block even if your default BlockState does not have a BlockEntity.

I'll concede this is an issue, but its very minor (affects just a small subset of creative players). That said, its worth a Neo patch if a conditional `hasBlockEntity` were to exist, probably solved automatically.

> WorldGenRegion#setBlock during the phase that is not ChunkType.LEVELCHUNK will create a CompoundTag with x, y, z, and "DUMMY" id to save at the spot even if the BlockState does not have a BlockEntity because hasBlockEntity returned true. This then causes ChunkAccess#getBlockEntitiesPos to report your block's position as a BlockEntity.

I'll concede this is an issue, but its worth a Neo patch if a conditional `hasBlockEntity` were to exist, probably solved automatically.

> LevelChunk#setBlockState would not remove the BlockEntity when switching from a BlockState with one to a BlockState without the BlockEntity when it is the same block each time. The patch here literally did nothing so this issue would exist in 1.19.2 anyway.

`onRemove` is easy to override to do that. Its not called client side IIRC, but somehow in my testing the block entity still got removed when I removed the serverside one, likely due to a packet sync.

> LevelChunk#createBlockEntity looks like it will call newBlockEntity on your BlockState without a BlockEntity to try and force create the BlockEntity. You would have to know this before-hand and return null when the state isn't what you want.

`Block#newBlockEntity` is the nullable method that allows conditional block states. This is not an issue.

> LevelChunk#getBlockEntity which calls LevelChunk#promotePendingBlockEntity looks like it will spam Tried to load a block entity for block {} but failed at location {} if a BlockState without the BlockEntity was placed during worldgen. It checks if "DUMMY" id exist for CompoundTag and if so, will call newBlockEntity on your BlockState without a BlockEntity to try and force create the BlockEntity. If you return null from this method, then the logspam will occur.

Yeah, but the block I have is problematic to place during worldgen anyways. Sounds like this is a case is worth a Neo patch though so other usecases could do it, probably solved automatically.

> BlockBehavior#onRemove would not remove the BlockEntity when switching from a BlockState with one to a BlockState without the BlockEntity when it is the same block each time. The patch here literally did nothing so this issue would exist in 1.19.2 anyway.

`onRemove` is easy to override to do that. So yes, the `onRemove` patch here does nothing.

----

So in summary:
* 1 non-issue as the conditional block entites are made possible by the nullable `createBlockEntity`. If it was not meant to be supported, why is it nullable?
* 2 cases solved by overriding the block method `onRemvoe`, though 1 of them I honestly have no idea why it works, it just worked in my testing.
* 4 cases solved by conditional `hasBlockEntity` without changes to vanilla code from my understanding of your explanation

----

> KnightMiner, I'm pretty sure the changes in this PR have no impact on your code.

In the current state of Neo without supporting conditional `hasBlockEntity`, no, it has no impact. However, if Neo was to allow me to override that to not just be an interface check, then those patches would become useful.

I suppose if Neo just decides that my usecase is entirely unsupported than I am convinced dropping these patches won't affect me. It just seems odd to drop support for this given it was supported not to long ago (notably around 1.16+ era).

**Comment by TelepathicGrunt** [comment]
@KnightMiner 
> I suppose if Neo just decides that my usecase is entirely unsupported than I am convinced dropping these patches won't affect me. It just seems odd to drop support for this given it was supported not to long ago (notably around 1.16+ era).

Please see @embeddedt's questions. We also wanted to know how you are even doing per-BlockState BlockEntities as well. Are you using mixins or something to make it possible or something.

**Comment by KnightMiner** [comment]
> @KnightMiner Please provide a code example of how one can create a per-blockstate BE; I do not see how it can be possible in 1.18/1.19, unless you are patching the game yourself to reintroduce it. It seems more likely the BE is still created but maybe doesn't tick or something.

Its entirely possible by just returning `null` from the `@Nullable` `EntityBlock#newBlockEntity` method, and then currently you also have to override `onRemove` as `hasBlockEntity` is not actually BlockState aware.

It strikes me as odd that the method would be nullable and mojang would have code checking for the currently unconditional but potentially conditional `hasBlockEntity` if it was not meant to support conditional block states.

For instance, this lovely block of code:
image

**Review by Technici4n — APPROVED** [review]

**Comment by TelepathicGrunt** [comment]
@KnightMiner I suspect it has something to do with the hacked together MovingPistonBlock. It's the only BlockEntity that returns null for `newBlockEntity`. And it does null for all of its state. In fact, it's block entity is only create-able from PistonBaseBlock. Nowhere else. Mojang probably did nullable return for that one block to make sure its block entity is handled like it doesn't exist for saving or other checks as the BlockEntity only exists for like a tick or so?

Nevertheless, making `hasBlockEntity` be state sensitive internally is not that bad of a patch but I would like to hear other Neo maintainer's thought process on if we should go that route.

**Comment by embeddedt** [comment]
We removed it in 1.17, presumably for a reason. We should find out what that was and determine whether the original reasoning is no longer valid. Notably, is there any practical benefit to allowing BEs per-state instead of just using separate blocks? I don't see one myself, aside from avoiding the need to refactor legacy code as noted above.

**Comment by TelepathicGrunt** [comment]
All I can find is this PR. Which looks just like our current patch. If hasTileEntity was not deferring to the block back then, even that PR wasn't doing any behavior change. 
https://github.com/MinecraftForge/MinecraftForge/pull/6674

Hmm nvm this appears to be in the block class...

Ok found the blockstate sensitive method. Time to find PR that removed it
https://github.com/MinecraftForge/MinecraftForge/blob/a3d50ff54554096674458d3724dbc984390d203b/src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java#L160

**Comment by embeddedt** [comment]
I am pretty sure it was removed during the 1.17 or 1.18 port alongside Mojang's changes to how blocks provide block entities, because it was deemed unnecessary, so you may struggle to find a certain PR.

**Comment by TelepathicGrunt** [comment]
Yep it was during a port. Reasons why I dislike squashes... Can find reasons for changes. Maybe we can find a hint of prior discussions in discord
https://github.com/MinecraftForge/MinecraftForge/commit/be5446b91c17a3dbed880028741c430610bd59f1#diff-926273cc479c8b0463d6d90c467b7a364f1482f0b2a63ec8a566480e5d4da46bL171

**Comment by HenryLoenwind** [comment]
Didn't we even have something along the lines of `canTileEntityStay(oldBlockstate, newBlockstate)` that allowed blocks to have different BEs for different blockStates and to allow different blocks to share the same BE? Not that I think bringing that back would be a good idea.

In general, I don't see any good reason to support this. It is quite trivial to split one block with many blockstates into many blocks with one blockstate each. The only reason to combine them into one block is if the BE needs to survive the transition, otherwise there's nothing you need states instead of blocks anymore. You're not even saving block IDs...

**Comment by TelepathicGrunt** [comment]
All I can find is these convos. Maybe people got confused and thought vanilla handles blockstate sensitive blockentities fully but failed to realized it actually doesn't with the hasBlockEntity method.
image

image

**Comment by TelepathicGrunt** [comment]
Honestly, this smells like the blockstate sensitive method on bock was removed due to a misunderstanding. I think I'll add it back as a separate followup PR. We can move our discussion there

**Comment by embeddedt** [comment]
Why add it back? It's an extra edge case to maintain on top of vanilla logic and I haven't seen a good argument for why it's needed after the flattening. (That it existed in 1.15/1.16 at all may just be a result of continuously porting legacy code.)

**Comment by KnightMiner** [comment]
My usecase is not having different block entities for different states, but rather the block entity not existing at all in certain states. To be precise, the block entity is just data storage used in combination with a multiblock system. Right now, all the multiblock logic needs to do is set the state that enables the block entity, then fetch the newly created block entity to add the relevant data. Splitting it means now I need to maintain a mapping from the block with no block entity to the block with a block entity to allow it to do that transition when the multiblock forms, and reverse that mapping when it breaks. Its possible, sure, but its so much extra work and would be way more prone to bugs due to missing registration or misaligning that mapping and alike.

Having different block entities based on the state would not care about a block state conditioned `hasBlockEntity`, since you'd return true in all cases, you'd just need to recreate the block entity in `onRemove` sometimes.

The flattening I'd argue is not relevant here, it was just about splitting blocks that had different item forms based on the state, they actually merged blocks that had the same item form but different IDs as part of it (notably slab/double slab blocks).

----

All that said, the question here is not whether I should do this, the question here is what should Neo support. From what I have seen, all Neo would have to do to support this usecase is add 1 patch to `BlockState` to allow blocks to override `hasBlockEntity` conditionally, and the rest of vanilla code would accept that. Is there a specific case in vanilla where being able to change that method would break? I struggle to see how this is a major maintenance burden.

**Comment by Technici4n** [comment]
Not sure we want to leave an open door to many edge cases like https://github.com/neoforged/NeoForge/pull/1369#issuecomment-2252695132 myself. Certainly this feature (some block states with a BE, some without) can be misleading, and most users will not find out about these edge cases until they get a painful bug report.

KM, why not have a block entity for every state?

**Comment by KnightMiner** [comment]
Those "many edge cases" are almost all solved by just having state sensitive hasBlockEntity, no additional patches needed. They are edge cases without the change only.

As for why, performance mostly. There is a small cost to a block having a BE which hinders using the block for decorating.

**Comment by lukebemish** [comment]
Unless I misunderstand something that seems like a perfect case for making it two different blocks? After all, even stuff like capabilities and whatnot can be maintained across both blocks with relative ease with the new system for those. The only cost is refactoring some legacy code -- while the necessary patch in neo to add a block state sensitive version at least a bit extensive, requires mod code to change to use the overloaded method as well, and also opens up a fun bit on unintuitiveness in a place where modders can currently just make the intuitive assumption.

**Comment by KnightMiner** [comment]
The cost is not just maintaining some legacy code. The cost is duplicating every resource related to the block. If I wanted two separate blocks, I'd have just created two separate blocks originally like RailCraft did back in the 1.7 days. Plus, separate blocks just open up a ton of potential bugs that I don't need to deal with in a single block.

> while the necessary patch in neo to add a block state sensitive version at least a bit extensive

Its literally 1 new method and a 1 line patch

> requires mod code to change to use the overloaded method as well

Only if you wish your your block state to be conditioned on different block state properties. For callers, they should already be calling the block state sensitive method because its a vanilla method, `BlockState#hasBlockEntity`

> and also opens up a fun bit on unintuitiveness in a place where modders can currently just make the intuitive assumption.

No, the current behavior is pretty unintuitive, the fact a method on block state is not block state sensitive. I'd immediately assume upon seeing the method that a blockstate might change it, else I'd expect it to be a block method.

**Comment by TelepathicGrunt** [comment]
So the plan looks to be that we can move forward with removing these patches because they literally do nothing. Does not help blockstate sensitive BEs at all nor do any logic change. It’s just dead code. 

However, I’ll write up a follow-up PR to do the patching to do blockstate sensitive blockentities and leave that up so @KnightMiner can use the build from it to test if it fixes and works properly with his blockstate sensitive blockentities when he ported to 1.21.

**Pull request merged**
