### PR TITLE
[1.21.4] Remove custom scrollable ExperimentsScreen

### PR DESCRIPTION
**Pull request by XFactHD**
This PR removes the custom `ScrollableExperimentsScreen` as it is superceded by vanilla's `ExperimentsScreen`. Apart from that, the existing implementation of the custom screen also causes a crash in the vanilla screen when any custom feature flags are present.

### CODE REVIEW

**Comment by Gaming32** [comment]
Mojang's experiments screen does not appear to scroll the buttons as the screen is scrolled, based on a code review. It only appears to scroll them visually, but they physically remain still (i.e. their "hitbox" doesn't move).

**Comment by XFactHD** [comment]
From a quick test that is indeed correct. I'll look into including a patch for that in this PR later.

**Comment by XFactHD** [comment]
I've pushed a workaround for the interaction issue. I really don't like the patch but I currently can't think of any better solution.

**Review by marchermans — APPROVED** [review]
Yeah annoying that we need so much patching to fix the offset handling of vanilla buttons, but whatever this fixes a set major bugs with our implementation of the screen by removing it, and fixes mojangs derp.

**Pull request merged**
