### PR TITLE
Rename EffectCures#getActions to EffectCures#getAllCures

### LINKED ISSUE #1038: Misnamed method `EffectCure#getActions`
`EffectCure`'s method returning all registered values is misnamed to `getActions` instead of `getCures`.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Misnamed method needed to be fixed

Closes https://github.com/neoforged/NeoForge/issues/1038

### CODE REVIEW

**Comment by KnightMiner** [comment]
Is it worth keeping the old name around as deprecated for removal so it's not a breaking change? Can remove it next breaking change window

**Comment by TelepathicGrunt** [comment]
That is true but on the other hand, it is a super quick rename modders can do and we are still technically in breaking change window. I'll wait to see what other maintainers think is ideal for this

**Comment by Spinoscythe** [comment]
we are in the beta phase right now so this is possible and passable imo

**Review by Matyrobbrt — APPROVED** [review]
Concur'd. We're in a beta phase, and this is a method that won't be frequently used by mods. It's fine to change it, as the current name is a copy-pasta error that doesn't even make sense.

**Pull request merged**
