### PR TITLE
[1.20.4] (Attempt to) Convert tools to data maps

### PR DESCRIPTION
**Pull request by Spinoscythe**
(Attempt to) Convert tool maps to data maps

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
~~Where did the name `flattenables` come from?  The name of the data map should reflect the vanilla method name `getShovelPathingState`, which would yield `shovel_paths`.~~

I see that's literally the vanilla field name.  Weird that it's disjoint from the method name (which is not the case for compost or stripped blocks).

**Comment by Shadows-of-Fire** [comment]
This PR needs to be rebased against 1.20.5 since feature development for 1.20.4 has concluded; in general the approach seems fine.  The main change I would make is extracting the patched-in hunks to a util method in `CommonHooks` so they can be documented appropriately.

**Comment by Spinoscythe** [comment]
this probably will be any day after May 16th since I've exams, so yeah it's gonna take a while.

**Comment by Spinoscythe** [comment]
I will redo this

**Pull request closed without merging**
