### PR TITLE
Simplify ChunkRenderTypeSet

### PR DESCRIPTION
**Pull request by embeddedt**
This PR simplifies `ChunkRenderTypeSet` by making several improvements:

1. Use an `int` bitfield internally instead of a `BitSet`. Since there are only 5 render types and they are registered statically, the `BitSet` provides no advantage and in fact reduces performance.
2. Since there are only 2^5 = 32 possible `ChunkRenderTypeSet` objects, the universe is now allocated once on class initialization rather than creating new sets for each call to `ChunkRenderTypeSet.of`.
3. Render type sets now cache an `ImmutableList` with all the render types they contain (this is essentially free given 2). It also allows the custom iterator to be removed in favor of just using the `ImmutableList`'s own iterator directly.

This should not break any mods, as none of the public API surface has changed.

### CODE REVIEW

**Review by Technici4n — APPROVED** [review]

**Comment by Technici4n** [comment]
Do you have some performance numbers for this?

**Comment by embeddedt** [comment]
I didn't profile the new implementation, however, the old implementation showed a nontrivial amount of time being spent in `BitSet.get` when `contains` was called. Doing the bit logic with an `int` directly as this PR does is virtually guaranteed to be faster. Also, there might be a *slight* benefit to the CPU cache having the render type sets deduplicated.

**Review by XFactHD — APPROVED** [review]

**Review by marchermans — CHANGES_REQUESTED** [review]
Putting this on hold for 24 Hours.
Discussing internally what the gain of this PR is, vs the loss of functionality as several people can not reproduce the proposed and theoretical gains.

Might be something related to CPU or RAM Architecture or volume. But this kind of change needs proper understanding as there might be other locations in the code where this is relevant.

Not rejected based on the PR contents itself. Those are fine.

**Comment by marchermans** [comment]
> Putting this on hold for 24 Hours. Discussing internally what the gain of this PR is, vs the loss of functionality as several people can not reproduce the proposed and theoretical gains.
> 
> Might be something related to CPU or RAM Architecture or volume. But this kind of change needs proper understanding as there might be other locations in the code where this is relevant.
> 
> Not rejected based on the PR contents itself. Those are fine.

This PR is on-hold.
Several maintainers pointed out that there does not seem to be any improvements on their systems, and these changes would block further API enhancements we are researching. On top of that the reason why this _should_ work on @embeddedt system is currently unclear. Until we gain a better understanding of why this micro-optimization works, we are turning this into a Draft.

**Comment by embeddedt** [comment]
Closing as this isn't worth implementing in NeoForge proper with the current performance data we have, and the API is not written in a way that prevents a mod from making the change if it so desires. Better to keep it generic for now to not block future work.

**Pull request closed without merging**
