### PR TITLE
Add an incompatible/discouraged clause to mod dependency

### PR DESCRIPTION
**Pull request by Matyrobbrt**
Depends on https://github.com/neoforged/FancyModLoader/pull/51
More information can be found in that PR.

### CODE REVIEW

**Comment by KnightMiner** [comment]
Can you give an example of the syntax (I assume in mods.toml) to declare such an incompatibly?

**Comment by Matyrobbrt** [comment]
The `mandatory` field is replaced by `type=optional/required`:
```patch
 [[dependencies.somemod]]
   modId="othermod"
   versionRange="[1,)"
-  mandatory=false
+  type="optional"
```

As for the incompatibility declaration:
```toml
[[dependencies.neotests]]
type="discouraged" # can be "incompatible"
modId="client_command_test"
versionRange="[1.4.3,)"
reason="We conflict because of reasons"
```
The version range can be omitted which will declare an incompatibility with all versions of the mod.

**Comment by Minecraftschurli** [comment]
eh I'm not really sure if I like the name `discouraged`

**Comment by Matyrobbrt** [comment]
The name is descriptive, it's quite literally what the feature does. It shows a screen discouraging the use of the mod. We've gone through different names and found this pair the best possible name, that also isn't extremely generic like `type="warn"` or `type="error"`.
(also, the SPI PR with that naming has already been merged, right now FML is waiting)

**Review by Minecraftschurli — APPROVED** [review]
dewit

**Pull request merged**
