### PR TITLE
Fix server installer

### LINKED ISSUE #38: Server Failure to Start - Duplicate key
**Minecraft Version:** 1.20.1

**Neo Forge Version:** forge-1.20.1-47.1.28-installer

**Logs:** Installer log: https://gist.github.com/AzureDoom/fd41749aca4121c446f18056dcb90c6c

**Steps to Reproduce:**
 1. Run installer
 2. Extract server files to new folder
 3. Try and Start server

**Description of issue:**
Trying to launch server files (run.bat ) gives: 
```
Exception in thread "main" java.lang.IllegalStateException: Duplicate key C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar (attempted merging values EmbeddedFileSystemMetadata[path=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fs=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fsCh=sun.nio.ch.FileChannelImpl@38bc8ab5] and EmbeddedFileSystemMetadata[path=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fs=C:\Users\AzureZhen\Desktop\New folder\libraries\net\neoforged\fancymodloader\loader\47.1.41\loader-47.1.41.jar, fsCh=sun.nio.ch.FileChannelImpl@687080dc])
        at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
        at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
        at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystem.<init>(UnionFileSystem.java:131)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystemInternal(UnionFileSystemProvider.java:115)
        at cpw.mods.securejarhandler/cpw.mods.niofs.union.UnionFileSystemProvider.newFileSystem(UnionFileSystemProvider.java:105)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:84)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:70)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:62)
        at cpw.mods.securejarhandler/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:54)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.lambda$main$6(BootstrapLauncher.java:99)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:93)
```

### PR DESCRIPTION
**Pull request by malte0811**
- `net.neoforged.fancymodloader:loader` is already an `installer` dependency, so adding it explicitly causes the "duplicate key" error (first commit).
- Once that is fixed, you get errors along the lines of `Missing language javafml version [24,] wanted by forge-1.20.1-47.1.57-universal.jar`. This can be fixed by adding the corresponding JARs to the `legacyClasspath` by making them `installer` dependencies (second commit); I do not understand the NF launch process well enough to say whether this is the "right" fix or just a workaround though. On the client all of these jars are passed in the "real" classpath (`-cp`), which I assume has a similar effect.
- This results in an error `Module fml_language_java reads more than one module named fml_core`, which can be fixed by adding `pluginLayerLibrary` and `gameLayerLibrary` dependencies to the `ignoreList` property (third commit). Again I am not sure whether this is the right solution, but it mirrors what is done in the client installations.

closes #38

### CODE REVIEW

**Comment by sciwhiz12** [comment]
While this PR gets most of the way there to getting the dedicated server running, an issue is still present which blocks the server from running _on Windows_: the FancyModLoader language providers aren't getting discovered by FML, leading to a crash as the `minecraft` system mod (provided by the FML Minecraft language provider) is missing.

In brief, I've determined the root cause to be the use of `File.separatorChar` in [FML's `FileUtils#matchFileName`](https://github.com/neoforged/FancyModLoader/blob/c355af1a1867744490795a6676d0e6b6426f63b3/loader/src/main/java/net/minecraftforge/fml/loading/FileUtils.java#L26). `File.separatorChar`'s value depends on the running operating system -- per [its javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#separatorChar), it is `/` (forward slash) on UNIX systems, and `\` (backslash) on Microsoft Windows systems.

However, the legacy classpath is always written using `/` forward slashes in [`Util#getArtifacts`](https://github.com/neoforged/NeoForge/blob/c3b3b665b251f8468ce440c662cddcd57bdb4ea1/buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/Util.groovy#L79). This means that the dedicated server is able to match the file names of the language providers (passed as the `fml.pluginLayerLibraries` system property) against the classpath _only on UNIX systems_ as `File.separatorChar` is `/` there.

I'm currently in the process of testing a fix in FancyModLoader for this. The PR author has consented to me or another maintainer updating this PR with the new FML version once that has been tested, merged, and published.

**Comment by sciwhiz12** [comment]
I've updated this PR with the version bump for FancyModLoader, as said above. I've tested the change locally, and it works -- the dedicated server now boots up fully.

**Comment by cpw** [comment]
This looks like the wrong solution to the problem. If I understand correctly, you basically fixed it by forcing all the modules into the legacy classpath instead. a COMPLETELY incorrect solution.

**Comment by malte0811** [comment]
It's the same solution the other launch setups I looked at (userdev server+client, prod client) use, so I assumed that it was the correct one. If this PR is not usable please close it, I will not be able to work on this for the next 1.5 weeks.

**Comment by cpw** [comment]
Please do not merge this in the current state or anything like it. this looks completely wrong. I will be investigating _tomorrow_.

**Review by cpw — CHANGES_REQUESTED** [review]
This is not the solution. There's a bigger picture issue.

**Comment by SizableShrimp** [comment]
I can say at the very least that duplicating the artifacts from the `pluginLayerLibrary` and `gameLayerLibrary` configurations to the `installer` configuration manually is not the way to go. These deps are already installed yet not properly added to the clas spath in the`win_args.txt` / `unix_args.txt` files that the server uses at startup. (This is a mistake from me when I implemented the feature initially at 5am 3 weeks ago.) The team will be looking into this with a close eye and our own fixes/cleanup in the next coming days. Thanks.

**Review by cpw — DISMISSED** [review]

**Comment by cpw** [comment]
OK. The fundamentals were correct - i was misinterpreting the classpath discussion. However, you can't futz with the installer configuration, because that breaks the client. You have to fix the server install to merge the LayerLibrary files into the CLASS_PATH, as well as fixing the ignore.

**Review by SizableShrimp — APPROVED** [review]

**Review by sciwhiz12 — APPROVED** [review]

**Pull request merged**
