### PR TITLE
Mod List Screen Cleanup

### PR DESCRIPTION
**Pull request by eerussianguy**
In these changes I've not made any changes to the appearance of the screen, it just is cleaning up the param names, code style, and then standardizing some of the repeated methods. Any further changes to the screen would need something like this so it's better to submit it separately.

The two interesting things are changing how the logo image is constructed, (now it matches how vanilla does it, eg. PackSelectionScreen), and using Component, since the screen class already seemed to switch between them freely and since the class is client side anyway.

### CODE REVIEW

**Comment by shartte** [comment]
Hm, in my personal opinion, I'd wait with PRs like this until automated code-styling is in-place. A lot of the diff is only related to reordered imports, brace and space-changes, etc.

**Comment by pupnewfster** [comment]
While I agree it likely makes sense to hold off on this until there have been some overall code styling decisions made on the project, I am leaving this comment here so that when it is time for something like this/if there is still enough cleanup that isn't just style changes we don't forget to also address the following:

One thing I noticed when looking at usages of methods is that [this line](https://github.com/neoforged/NeoForge/blob/f8092d06934ee33e420e5d23cc1c3710e1029737/src/main/java/net/minecraftforge/client/gui/ModListScreen.java#L155) should be able to be replaced with just `ret.addAll(font.split(chat, maxTextLength));`

**Comment by Technici4n** [comment]
Hi, can you update this PR to 1.20.2 now that we have an automated code formatter?

**Comment by embeddedt** [comment]
This PR has been inactive for quite some time, and is now very out of sync compared to the `1.20.x` branch. Please open a new PR if you are still interested in making any of these changes.

**Pull request closed without merging**
