### PR TITLE
Added method to make creating faces on models less annoying

### PR DESCRIPTION
**Pull request by ArcAnc**
> Continuation of #1212.

Added simple small method for situations, when user don't need all faces for one model part. 

In situations like this: 
```java
                element().
                    from(7,6,7).
                    to(9, 7, 9).
                    face(NORTH).end().
                    face(SOUTH).end().
                    face(WEST).end().
                    face(EAST).end().
                    face(UP).end().
                    faces((face, builder) ->
                    {
                        builder.texture("#button");
                        if (face != UP)
                            builder.uvs(0,8, 8,12);
                        else
                            builder.uvs(0, 0, 8, 8);
                    }).
                end()
```

when one or more sides is not needed syntax will be much easier:
```java
                element().
                    from(7,6,7).
                    to(9, 7, 9).
                    allFacesExcept((face, builder) ->
                    {
                        builder.texture("#button");
                        if (face != UP)
                            builder.uvs(0,8, 8,12);
                        else
                            builder.uvs(0, 0, 8, 8);
                    }, EnumSet.of(DOWN)).
                end()
```

### CODE REVIEW

**Review by embeddedt — COMMENTED** [review]
What benefit does this bring over using `allFaces` and just adding an `if(face == DOWN) return;` at the top of the consumer? That is just as explicit and still avoids listing all the faces.

```java
                element().
                    from(7,6,7).
                    to(9, 7, 9).
                    allFaces((face, builder) ->
                    {
                        if(face == DOWN)
                            return;
                        builder.texture("#button");
                        if (face != UP)
                            builder.uvs(0,8, 8,12);
                        else
                            builder.uvs(0, 0, 8, 8);
                    }).
                end()
```

**Comment by ArcAnc** [comment]
@embeddedt lets look at the resulting model file. In your case result will be looks like this: 

```json    
{
      "faces": {
        "east": {
          "texture": "#button",
          "uv": [
            8.0,
            8.0,
            16.0,
            12.0
          ]
        },
        "down": {
          "texture": "minecraft:missingno"
        },
        "north": {
          "texture": "#button",
          "uv": [
            8.0,
            8.0,
            16.0,
            12.0
          ]
        },
        "south": {
          "texture": "#button",
          "uv": [
            8.0,
            8.0,
            16.0,
            12.0
          ]
        },
        "up": {
          "texture": "#button",
          "uv": [
            8.0,
            0.0,
            16.0,
            8.0
          ]
        },
        "west": {
          "texture": "#button",
          "uv": [
            8.0,
            8.0,
            16.0,
            12.0
          ]
        }
      },
```
when in my variant "down" will be removed from model file. Yes, it's changing almost anything, but for each useless model face, especially in big models and big projects it will be significant amount of saving space on disc.

**Comment by TelepathicGrunt** [comment]
If file size savings is your main concern, wouldn't it make more sense to have empty objects not be written to json for various datagen automatically?

**Comment by ArcAnc** [comment]
@TelepathicGrunt Saving space in files is not my main goal, rather a pleasant side effect obtained thanks to the added method. As I said, method offered by @embeddedt will be add empty objects, when my method does not

**Comment by TelepathicGrunt** [comment]
@XFactHD thoughts on this PR? Embeddedt is neutral on it.

**Comment by XFactHD** [comment]
I would be in favor of this, in part because I ran into a use case for this in the past where I was very close to contributing it myself and also because I'm fairly certain that the model file shown above which is created by the suggested alternative solution does not actually do what's desired here: I'm pretty sure the almost empty `down` face will actually render as the model loading system will deduce the face UVs from the face coordinates if no explicit UVs are specified.

**Comment by KnightMiner** [comment]
I feel like it be better to fix the existing `allFaces` logic to not add the face if it was skipped in the builder. Perhaps you base it on the texture being `missingno` and no other fields in the face?

Not sure how difficult that would be to accomplish, but it would have the nice benefit of allowing more advanced logic for faces, e.g. `if (face.getAxis() == AXIS.Y || face == Direction.SOUTH) continue;`

**Comment by ArcAnc** [comment]
@KnightMiner it's much more easy just add my function and use it for this thing

@XFactHD 
> I'm pretty sure the almost empty down face will actually render

You are right. Even with missing texture it will be rendered, just because model loader can find those face, which means it must rendered with default uv (0,0,16,16)

**Comment by KnightMiner** [comment]
The default UV is actually just transforming the `"to"` and `"from"` from the parent element, not 0,0 to 16,16. That is, unless for some reason the Neo model builder changes the default to not be empty, which would be a weird choice.

In either case, yes, a face with just a texture is a valid face.

**Comment by XFactHD** [comment]
> I feel like it be better to fix the existing `allFaces` logic to not add the face if it was skipped in the builder. Perhaps you base it on the texture being `missingno` and no other fields in the face?

I don't think such heuristic checks are a particularly great idea.

**Comment by ArcAnc** [comment]
So, any news about merging?

**Review by XFactHD — APPROVED** [review]

**Pull request merged**
