### PR TITLE
[1.21.3] Show a range's default value in config file

### LINKED ISSUE #1643: Config file should mention the default value next to the range
i think there is nothing more to explain

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Closes https://github.com/neoforged/NeoForge/issues/1643

### CODE REVIEW

**Comment by Technici4n** [comment]
Can you show an example of what this looks like? We could also put it on the same line as something else. For example:
```
# Configure how much power the machine needs. (Default: 3)
# Range: 1-5.
```

**Comment by TelepathicGrunt** [comment]
Was taking me a while to launch game with example.
image

That is what is looks like. I would encourage *not* putting it on the same line as the modder created config. That will be gross.

Either same line as range somehow or below range

**Comment by Technici4n** [comment]
How about default first and then range? It doesn't really matter I know 😅

**Comment by TelepathicGrunt** [comment]
visual aid
image

**Review by Technici4n — APPROVED** [review]

**Comment by Technici4n** [comment]
We can merge tomorrow to give more time for feedback.

**Comment by Shadows-of-Fire** [comment]
Thoughts on making it `# Default` (With a space) and applying the same change to `# Range` as well?  That seems to be more consistent with the placement of the user-provided comment.

**Pull request merged**
