### PR TITLE
Make custom ingredients never return `true` from `Ingredient#isEmpty`

### LINKED ISSUE #841: If craft with dye. Different Item Crafted
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.0-beta

**Logs:** none

**Steps to Reproduce:**
 1. Craft Item With Dye(like dye the item recipe such as carpet)
 2. different Item Crafted

**Description of issue:**
here is what happened when craft with dye item

### PR DESCRIPTION
**Pull request by PlatinPython**
Currently when creating a new `Ingredient` with the constructor for `ICustomIngredient`, `Ingredient#values` is initialized to an empty array.
This causes `Ingredient#isEmpty` to return `true`, which causes `StackedContents.RecipePicker` to remove it from the list of ingredients and as such match any item.
This PR makes custom ingredients never return `true` from `Ingredient#isEmpty`.

Fixes #841

### CODE REVIEW

**Review by Technici4n — CHANGES_REQUESTED** [review]
I don't think that this is the correct fix. Custom ingredients should never return true from `isEmpty`. I thought I had already changed that but presumably forgot to regen patches?

Additionally, we should convert empty compound ingredients to `Ingredient.EMPTY` when deserializing them in `CraftingHelper` to respect vanilla parity.

**Comment by Technici4n** [comment]
I think it would also be wise to add a few tests here that validate this fix and other potentially related changes, such as converting empty compound ingredients to `Ingredient.EMPTY`.

**Comment by PlatinPython** [comment]
Alright, I was uncertain what the best fix for that is. I'll look into making the necessary changes.

**Comment by Technici4n** [comment]
This is fine. Are you going to add a test as well?

**Comment by Technici4n** [comment]
In any case, consider that https://github.com/neoforged/NeoForge/pull/853 changes the serialization logic a bit.

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
