### PR TITLE
Tag cleanup and additions for 1.21

### LINKED ISSUE #919: Redundant tags for raw storage blocks
**Minecraft Version:** 1.20.6

**NeoForge Version:** 20.6.24-beta

**Description of issue:**

Neo currently has two sets of tags for raw ore blocks: [`storage_blocks/raw_`](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/Tags.java#L559-L561) ([with a block form](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/Tags.java#L213-L215)) and [`raw_blocks/`](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/Tags.java#L496-L499) (only item form, no block). Both just contain the vanilla raw blocks, and neither has any javadocs explaining the distinction, leading to modders being unsure of which one to use.

I think the storage block tag pretty clearly means it can be converted to and from the raw ore item, just like other storage block tags. However, raw blocks is unclear as we lack examples that are not vanilla.
* The best answer I could get was that raw blocks are blocks that can drop 1 or more raw ore when mined, however that definition was unsatisfying to me as raw ore blocks do not drop raw ore (they drop themselves) and regular ores drop 1 or more raw ore items (but are not tagged as raw blocks). Plus, `raw_blocks/` is exclusively an item tag, talking about block drops with an item tag does not make sense.
* I was also told the tags exist because they came from Fabric, however Fabric lacked a mirror to the raw storage block tags suggesting the tags potentially should have just been merged with the forge tag for these vanilla block.

Thus, I propose we take one of the following actions:
* Remove the `raw_blocks/` tags as they lack any conventions tied to their usage. Since are not in a breaking change window, that would consist of deprecating for removal until the next breaking changes window.
* Document exactly what it means to be a raw block, and how that is different from raw storage blocks and ore blocks and potentially make it a block tag as well. Make it clear what guarantees the tag provides and what other tags are required to make the tag meaningful (e.g. do we need to do tag intersection like with ores for sizes?)

### LINKED ISSUE #993: Add `c:music_discs` in 1.21
Mojang removed the tag. I think it was worth having for things like dropping a random music disc from a musical mob or spawning a random music disc in special chests or music disc input recipes
image

https://github.com/FabricMC/fabric/issues/3790

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
With 1.21 shaping up to be another large breaking change for many modders, we can use this for our advantage to do some tag cleanup work. This is paired up with this PR: https://github.com/FabricMC/fabric/pull/3807

The changes includes:

- Adding a `c:music_discs` tag since vanilla is removing `minecraft:music_discs` in 1.21. A log warning was added for this so people know they can migrate over to the c tag for music disc stuff that should not be reliant on the JUKEBOX_PLAYABLE item component.

- `raw_blocks` item tags are removed because the `storage_blocks` tag for the raw blocks already exist and is the same. Log warning added for this migration cleanup. The removal of these tags should reduce confusion in this area for modders.

- Removed Eroded Badlands from Sparse Vegetation Overworld since the biome has no trees at all and that normal badllands and desert isn't in the tag in first place.

- Tool tags were misspelled. So instead of `c:tools/bows`, it should had been `c:tools/bow` because tools is the noun to be plural and bow is the adjective. So it would read as Bow Tools instead of the awkward Bows Tools. 

- Added Shulker Boxes item tag, Glazed Terracotta block/item tag, Concrete block/item tag, Concrete Powder item tag.

Please comment here if there's any change here that you dislike or love! Or if you have suggestions of new tags to add, to sync from other loader, or should also be removed/adjusted.

See the below issue reports for more details and reasoning for each of this PR's changes:

Closes https://github.com/neoforged/NeoForge/issues/993
Closes https://github.com/neoforged/NeoForge/issues/919

### CODE REVIEW

**Comment by Spinoscythe** [comment]
@TelepathicGrunt is it possible to add `#c:has_wolf_variant/<variant>` biome tags?

**Comment by TelepathicGrunt** [comment]
@Spinoscythe There's a bit more to that tag than just existing. If added, and a modder adds to the tag, nothing happens. So every modder adding to that tag has to override the wolf variant files to point to the tag. Which is a bit weird for a modloaders to force modders to do.
https://github.com/misode/mcmeta/tree/data-json/data/minecraft/wolf_variant

So instead, adding wolf variant tags means modloaders would need to override the wolf variant files to point to the new c tags. The datapackers would use the same tag and they would be overriding the wolf variant files themselves. But modders wouldn't need to do the overriding.

However, the question becomes, is this vanilla behavior change something Neoforge and Fabric want to do? Well, behavior change that it points to a new tag that uses the same content as the old tag. The in-game behavior would be same by default

**Comment by Spinoscythe** [comment]
also, what's stopping us from doing this in 20.6?

**Comment by Spinoscythe** [comment]
> @Spinoscythe There's a bit more to that tag than just existing. If added, and a modder adds to the tag, nothing happens. So every modder adding to that tag has to override the wolf variant files to point to the tag. Which is a bit weird for a modloaders to force modders to do.
> https://github.com/misode/mcmeta/tree/data-json/data/minecraft/wolf_variant
> 
> So instead, adding wolf variant tags means modloaders would need to override the wolf variant files to point to the new c tags. The datapackers would use the same tag and they would be overriding the wolf variant files themselves. But modders wouldn't need to do the overriding.
> 
> However, the question becomes, is this vanilla behavior change something Neoforge and Fabric want to do? Well, behavior change that it points to a new tag that uses the same content as the old tag. The in-game behavior would be same by default

I would love to see more discussions on this.

**Comment by TelepathicGrunt** [comment]
removing/replacing tags (this this PR is doing) that both loaders should be sharing is a bit better to do with new mc version imo. And wolf variant tags would require messing with vanilla files so that could break people's expectations. Also, 1.21 is coming pretty soon too so seems better to plan for it and give time for people to discuss their stances and options

**Comment by TelepathicGrunt** [comment]
Tool tags were misspelled. 

so instead of `c:tools/bows`, it should had been `c:tools/bow` because tools is the noun to be plural and bow is the adjective. So it would read as Bow Tools instead of the awkward Bows Tools.

**Review by Technici4n — DISMISSED** [review]

**Comment by TelepathicGrunt** [comment]
@Technici4n Apologies. Had forgot to add the 1.21 music discs when I updated this to 1.21 branch. Ready to merge now with your approval

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
