### PR TITLE
[20.2] Cleanup vanilla bugfixes

### LINKED ISSUE #201: Remove bug fixes for Minecraft Vanilla (because fixed), or give more information about why they are left.
1.20.1:

* https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/client/renderer/texture/TextureManager.java.patch#L7 -> 1.20 pre-3 (MC-98707)
image

?

* https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/entity/ExperienceOrb.java.patch#L17
	-> [MC-53850](https://bugs.mojang.com/browse/MC-53850)

* https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/entity/LivingEntity.java.patch#L591
	-> [MC-2518](https://bugs.mojang.com/browse/MC-2518)

* https://github.com/neoforged/NeoForge/blob/ca32d0b452c9a7723ffa8766b6d3f2ab1ed0d13e/patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch#L23 
-> [MC-10657](https://bugs.mojang.com/browse/MC-10657)

* https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/entity/vehicle/Boat.java.patch#L72 
	-> *[MC-119811](https://bugs.mojang.com/browse/MC-119811) ->* [MC-103672](https://bugs.mojang.com/browse/MC-103672)

https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/extensions/IEntityExtension.java#L141 -> https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/extensions/IEntityExtension.java#L149

Turbo, Mojira moderator:
image

### PR DESCRIPTION
**Pull request by XFactHD**
This PR cleans up a few vanilla bugfixes. See summary below for why a fix was touched or not with links to the issues, line references in the source and patch links.

### Resolved as fixed - fix removed

- `ClientPacketListener`/`LocalPlayer`
  - [MC-10657](https://bugs.mojang.com/browse/MC-10657) (`ClientPacketListener` source line [1115](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/multiplayer/ClientPacketListener.java.patch#L23), `LocalPlayer` source line [1127](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/player/LocalPlayer.java.patch#L104-L114)): marked as resolved since 1.14.2 - fix removed, tested as working
- `TextureManager`
  - [MC-98707](https://bugs.mojang.com/browse/MC-98707) (source line [161](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/renderer/texture/TextureManager.java.patch#L7)): marked as resolved (no version specified) - fix removed, provable as fixed (unpatched vanilla code uses `Map#remove()` now)
- `ExperienceOrb`
  - [MC-53850](https://bugs.mojang.com/browse/MC-53850) (source line [186](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/ExperienceOrb.java.patch#L17)): marked as resolved since 1.18.1 - fix removed, provable as fixed (`Entity#isRemoved()` is checked in `Entity#isInvulnerable()` which is called from the now unpatched method, `Level#isClientSide` is checked in the now unpatched method itself)
- `LivingEntity`
  - [MC-2518](https://bugs.mojang.com/browse/MC-2518) (source line [3090](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/LivingEntity.java.patch#L590-L595)): marked as resolved since 19w14a (1.14 snapshot) - fix removed, tested as working
- `Boat`
  - [MC-119811](https://bugs.mojang.com/browse/MC-119811)/[MC-103672](https://bugs.mojang.com/browse/MC-103672) (source line [905](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/vehicle/Boat.java.patch#L72-L80)): marked as resolved since 19w38a (1.15 snapshot) - fix removed, tested as working with reasonable confidence

### Resolved as fixed - not modified

- `BeehiveBlock`
  - [MC-227255](https://bugs.mojang.com/browse/MC-227255) (source line [76](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/level/block/BeehiveBlock.java.patch#L7-L9)): marked as resolved since 23w40a (1.20.3 snapshot) - can only be removed in 1.20.3 ([Snowman](https://github.com/neoforged/Snowman/blob/d74264a57ee4b7c7518bc1bc11cce85d622eba68/src/main/java/net/minecraft/world/level/block/BeehiveBlock.java#L303-L309))
- `IEntityExtension`/`Entity`
  - [MC-136995](https://bugs.mojang.com/browse/MC-136995) (`IEntityExtension` source lines [128-152](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/src/main/java/net/neoforged/neoforge/common/extensions/IEntityExtension.java#L128-L152), `Entity` source lines [3521-3535](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/Entity.java.patch#L600-L614)): supposedly resolved as fixed. The issue is private, there are no known reproduction steps and it's unclear whether call sites of `IEntityExtension#isAddedToWorld()` are safe to replace with other options. As it can't be proven as fixed, the code requiring the mentioned super call was not removed

### Unresolved - modified

- `RailBlock`/`PoweredRailBlock`
  - [MC-196102](https://bugs.mojang.com/browse/MC-196102) (`RailBlock` source line [54](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/level/block/RailBlock.java.patch#L7-L9), `PoweredRailBlock` source line [181](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/level/block/PoweredRailBlock.java.patch#L70-L72)): unresolved, modified to point at the non-duplicate: [MC-104231](https://bugs.mojang.com/browse/MC-104231)

### Resolved as invalid or won't-fix - unknown validity

- `AbstractContainerScreen`
  - [MC-146650](https://bugs.mojang.com/browse/MC-146650) (source lines [579-592](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/gui/screens/inventory/AbstractContainerScreen.java.patch#L135-L152)): resolved as invalid due to misunderstanding of the return value of `AbstractContainerScreen#keyPressed()`, appears to still fix an issue related to dropping though
- `CatSpawner`
  - [MC-147659](https://bugs.mojang.com/browse/MC-147659) (source line [87](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/npc/CatSpawner.java.patch#L7-L9)): resolved as won't-fix, may need discussion

### Unresolved or resolved as invalid - still valid (no tests performed, only rough code analysis)

- `WorldSelectionList`
  - [MC-251068](https://bugs.mojang.com/browse/MC-251068) (source line [571](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/gui/screens/worldselection/WorldSelectionList.java.patch#L25)): unresolved
- `LocalPlayer`
  - [MC-231097](https://bugs.mojang.com/browse/MC-231097) (source line [298](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/player/LocalPlayer.java.patch#L15)): unresolved
- `GameRenderer`
  - [MC-250858](https://bugs.mojang.com/browse/MC-250858) (source line [823](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/renderer/GameRenderer.java.patch#L44-L54)): resolved as invalid
- `LightTexture`
  - [MC-169806](https://bugs.mojang.com/browse/MC-169806) (source line [197](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/renderer/LightTexture.java.patch#L17)): unresolved
- `SpriteCoordinateExpander`
  - [MC-263524](https://bugs.mojang.com/browse/MC-263524) (source lines [21, 27, 33, 39, 45, 51](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/client/renderer/SpriteCoordinateExpander.java.patch)): resolved as invalid due to no vanilla impact,
- `RegistryCodecs`
  - [MC-197860](https://bugs.mojang.com/browse/MC-197860) (source line [51](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/core/RegistryCodecs.java.patch#L8-L9)): unresolved
- `ServerPlayer`
  - [MC-46486](https://bugs.mojang.com/browse/MC-46486) (source line [1437](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/server/level/ServerPlayer.java.patch#L147)): unresolved
  - [MC-231097](https://bugs.mojang.com/browse/MC-231097) (source line [1745](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/server/level/ServerPlayer.java.patch#L289)): unresolved
- `RconConsoleSource`
  - [MC-7569](https://bugs.mojang.com/browse/MC-7569) (source line [38](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/server/rcon/RconConsoleSource.java.patch#L7-L8)): unresolved
- `PathNavigation`
  - [MC-94054](https://bugs.mojang.com/browse/MC-94054) (source lines [231](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/ai/navigation/PathNavigation.java.patch#L7-L8), [233, 234](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/ai/navigation/PathNavigation.java.patch#L10-L13)): unresolved
- `WallClimberNavigation`
  - [MC-94054](https://bugs.mojang.com/browse/MC-94054) (source line [48](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/ai/navigation/WallClimberNavigation.java.patch#L7-L14)): unresolved
- `SkeletonTrapGoal`
  - [MC-206338](https://bugs.mojang.com/browse/MC-206338) (source line [32](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/animal/horse/SkeletonTrapGoal.java.patch#L7-L18)): unresolved
- `EnderDragon`
  - [MC-158205](https://bugs.mojang.com/browse/MC-158205) (source lines [107, 113](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/boss/enderdragon/EnderDragon.java.patch#L7-L14), [928](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/boss/enderdragon/EnderDragon.java.patch#L76)): unresolved
- `Player`
  - [MC-168573](https://bugs.mojang.com/browse/MC-168573) (source line [925](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/entity/player/Player.java.patch#L150)): unresolved
- `EnchantmentHelper`
  - [MC-248272](https://bugs.mojang.com/browse/MC-248272) (source lines [175](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch#L45), [187](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch#L53)): unresolved
- `CampfireBlock`
  - [MC-201374](https://bugs.mojang.com/browse/MC-201374) (source line [268](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/level/block/CampfireBlock.java.patch#L7-L8)): unresolved
- `ChestBlock`
  - [MC-134110](https://bugs.mojang.com/browse/MC-134110) (source line [378](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/level/block/ChestBlock.java.patch#L7-L9)): unresolved
- `TripWireHookBlock`
  - [MC-129055](https://bugs.mojang.com/browse/MC-129055) (source line [168](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/patches/net/minecraft/world/level/block/TripWireHookBlock.java.patch#L7-L9)): unresolved
- `IItemExtension`
  - [MC-176559](https://bugs.mojang.com/browse/MC-176559) (source line [537](https://github.com/neoforged/NeoForge/blob/f2ba0dcc886bce243f5b17b2617e52449692a3d7/src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java#L537-L561)): unresolved

Closes #201

### CODE REVIEW

**Comment by Technici4n** [comment]
Regarding MC-136995, I found the relevant commit: https://github.com/neoforged/NeoForge/commit/958bbf6c9a3c55aa2a1543679f95b4b985a31ed3.

Regarding [MC-147659](https://bugs.mojang.com/browse/MC-147659), we should probably get Mojang to reopen the issue. One might ask how such a trivial patch ended up in Forge in the first place...

The rest looks good. (Didn't look too much at the still valid list)

**Comment by Technici4n** [comment]
Ok so for MC-136995:
- it seems that the only remnant of it is `      if (this.isAddedToWorld() && !this.level.isClientSide && !this.isRemoved()) this.level.getChunk((int) Math.floor(p_20344_) >> 4, (int) Math.floor(p_20346_) >> 4); // Forge - ensure target chunk is loaded.
` in `Entity`, source line 3335. We should check whether this still makes sense or not.
- it is generally nice to be able to check whether an entity is in a world - unless you say that there is another way?

**Comment by XFactHD** [comment]
- At a glance, I can't see anything that would replace this enforcement of the chunk being loaded. Would need to properly disect the entire `Entity` class, which I don't have the mental power for right now
- The only thing that comes somewhat close is `Entity#isRemoved()` but that also returns true on freshly created entities which have not yet been added to the level, so there's definitely merit in keeping the flag with its setters and getter in my opinion

**Comment by Technici4n** [comment]
Do we want to check if the MC-136995 code still makes sense, or should we go ahead with the PR as is?

**Comment by XFactHD** [comment]
I would say keep it for now. I haven't been able to make sure that the patch is actually redundant and through the addition of the `isAddedToWorld()` flag and its getters and setters it adds something that's also useful to mods and not just the bugfix

**Review by Technici4n — APPROVED** [review]

**Pull request merged**
