### PR TITLE
Change FE to use `long` with 64-bit support

### PR DESCRIPTION
**Pull request by cwielder**
This change significantly increases the amount of throughput the FE API can handle which lifts limitations that may be imposed on high-end tech mods.

### CODE REVIEW

**Review by Technici4n — COMMENTED** [review]
I love it. Unfortunately it won't happen.

Maybe look at https://github.com/AztechMC/Modern-Industrialization/blob/1.20/src/main/java/aztech/modern_industrialization/api/energy/ILongEnergyStorage.java for inspiration, I'm planning on publishing it as a separate lib at some point.

**Comment by marchermans** [comment]
I don't see a reason to change this.
99% of the mods use small amounts of power per tick, using longs causes a lot of memory consumption for no gain what so ever.

**Comment by Technici4n** [comment]
The memory usage argument is kinda bullshit (it's what Lex used). A single number is very cheap regardless of long or int. The argument people usually give is balance.

**Comment by Technici4n** [comment]
Typically, mods use an int amount per tick. However the energy storage can easily go above an int.

**Comment by FinnT730** [comment]
I know that I am not a member of the NeoForge team, but @TheSilkMiner DID point out that it would be a waste of time to make a PR for it ([seen here](https://discord.com/channels/313125603924639766/1116211620415283201/1208335851776380929))
Just wanted to point that out...

**Comment by sciwhiz12** [comment]
I think issues of balance is going to be the primary deciding factor for this PR. As I understand it, there are already energy balancing issues present in the modding landscape, as mods often do some form of one-upmanship over others to try make their mod more appealing. Moving from `int` to `long`, besides the compatibility issues, would give a lot more room, and therefore might cause larger and larger gaps of energy balance.

I personally would not merge this PR unless there is clear community consensus on this regard.

**Comment by cwielder** [comment]
Is it really the modding API's responsibility to make decisions about mod gameplay balancing though?

**Comment by TheSilkMiner** [comment]
My two cents on this: why is this needed? Granted, the limitation of int is arbitrary, but so are other limits in other places (fluid tanks to name another Neo API, stack size in vanilla, or burn time). Moreover, high end tech mods don't necessarily have to leverage Forge Energy if it doesn't fit their needs, such as requiring higher throughput, rather they can implement their own thing and provide a lower throughput interface through FE (or just don't provide support entirely).

I personally don't have any strong opinion on int vs long, but I do think that at least some more use cases should be provided other than "bigger limit because it can be bigger".

**Comment by cwielder** [comment]
Of course a custom API could be created by each mod that wants to handle large amounts of energy but then they wouldn't be compatible with each other except through the bottlenecked FE API. An example can be see by the code that Technici4n linked which demonstrates that such high-end tech mods do exist, and so inter-compatibility (which *is* the responsibility of neoforge as opposed to balance) should be handled by providing a better official API

**Comment by TelepathicGrunt** [comment]
Making a bigger limit just invites mods to increase their power output annnnnd you’re back to square one with mods hitting the long limit and now asking for BigIntenger limit. 

The power creep scale of mods had long been out of control. Maybe it’s the mods that should be rebalancing themselves rather than unlocking the limit and making the ecosystem worse for players

**Comment by Shadows-of-Fire** [comment]
Well we could have this discussion forever, ultimately this isn't something we're interested in pursuing.

**Pull request closed without merging**
