### PR TITLE
Add `c:tools/melee_weapon`,  `c:tools/ranged_weapon`,  and `c:tools/mining_tool` tool tags

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
- Adds `c:tools/mace` to `c:tools` explicitly to match how we are doing the other tags in there.

- Adds `c:tools/melee_weapon`,  `c:tools/ranged_weapon`,  and `c:tools/mining_tool` tags to both match Fabric and help provide more categorization that can prove useful for recipes and loot tables. This does not replace ItemAbilities. Rather it is compliment to it. Also, I have mining boots myself but they don't really fit the `pickaxe_dig` ItemAbility so tagging may be a more clear concept here for it as the boots digs when worn and crouched. Not held in hand and mining like a pickaxe does mining.

### CODE REVIEW

**Review by Minecraftschurli — CHANGES_REQUESTED** [review]
LGTM but is there an accompanying PR to fabric? If so what is its state?

**Comment by TelepathicGrunt** [comment]
@Minecraftschurli fabric already has these tags. This is to make Neo match fabric more

**Review by Minecraftschurli — APPROVED** [review]
If fabric already has them :shipit:

**Comment by Kanzaji** [comment]
Hey there! 
From curiosity, why were new tags created with use of Item ResourceLocations instead of vanilla tags 😅?

**Comment by TelepathicGrunt** [comment]
@Kanzaji can you please explain more of what you mean exactly?

**Comment by Kanzaji** [comment]
Was curious why new tags were created by adding vanilla tools manually, instead of using already-existing tags that include all of the items of that type. Example:
`#c:tools/mining_tool` -> `#minecraft:pickaxes`
`#c:tools/melee_weapon` -> `#minecraft:swords`, `#minecraft:axes`, `#c:tools/mace`

I'm terrible at explaining as you can see, but this I think gives you the idea of what I meant with the original question 😅
I think this would make sense, as if some item has `#minecraft:pickaxes` tag (for example), it is a mining tool by the definition.

**Comment by TelepathicGrunt** [comment]
One could make a sword that shoots a projectile but no actual melee attack. Is it is better not to make assumptions off of the tool type and instead have modders specifically put their tool in the actual tag that describes it. That’s why I didn’t want to chain tags here as modders could do all sorts of unique tools that break out of the typical behaviors

**Pull request merged**
