### PR TITLE
Release with actions

### PR DESCRIPTION
**Pull request by Matyrobbrt**
All of our projects but NeoForge and NeoGradle are built and released with actions. NeoGradle will keep being built with TC for now due to the functional tests killing action workers, but NeoForge has no such need, and it already tests PRs with actions.

### CODE REVIEW

**Review by marchermans — CHANGES_REQUESTED** [review]
When we discussed the previous migration journeys, a discussion, before the migration was done, was agreed upon. Because of two reasons:

1) It is not worth maintaining two CI systems, but right now we can't get rid of both due to limits in GA.
2) We are still unsure if the new testing setup won't cause this project to blow out of its limits. Yes we might be in it now, but if we do worldgen tests, or other long running tests, then we might run out of its limits.

This makes me in principal against migrating right now.

**Comment by Matyrobbrt** [comment]
This PR simply migrates releasing to actions, and releases have never ran tests, so tests wouldn't affect this.
PRs are already running tests through actions and we require that PRs are both up-to-date when merged and that they pass the gametests before being merged.

**Review by Technici4n — DISMISSED** [review]

**Review by marchermans — DISMISSED** [review]
Approved by internal discussion.
Of note:

I objected in practice not to the content of this PR, as of its scope it is basically good.

**Review by Minecraftschurli — DISMISSED** [review]
Maty :shipit:

**Review by sciwhiz12 — APPROVED** [review]

**Pull request merged**
