### PR TITLE
[1.20.4] Move `BuildCreativeModeTabContentsEvent` out of client-only code

### LINKED ISSUE #9662: CreativeModeTabs are NOT a client only class yet they call forge client only events making them effectively be one.
As I've said CreativeModeTabs are a class that dont get stripped and isnt marked as client only. In previous versions one could access their condent on a logical server for various reasons (such as getting all items that were "intented" to be show ingame, grouping items by their categories to give to players and such).
From 1.20 forge calls ` ForgeHooksClient.onCreativeModeTabBuildContents()`, a method which loads a bunch of client classes making the entire process fail. This isnt even "fool proof" as one might accidantally calls any of those methods that rebuild content for whatever reason (whcih is totally valid as as I've said those are not in the client package)
I suggest to just move the event out of that client hooks class into the common one making it server safe

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
Fixes https://github.com/MinecraftForge/MinecraftForge/issues/9662

### CODE REVIEW

**Review by Minecraftschurli — APPROVED** [review]
:shipit:

**Comment by Matyrobbrt** [comment]
While we're changing this, is it necessary to fire the event in the mod bus? Unlike the other events this isn't really a "registration event" in that sense as it could fire multiple times over the lifespan of the game.

**Comment by Shadows-of-Fire** [comment]
It being a mod bus event did strike me as a little bit weird.

**Comment by Technici4n** [comment]
Changing the bus is best done in bulk once we update the policy. We should strive to limit breakage at the moment.

**Comment by MehVahdJukaar** [comment]
Can this be backported to 1.20.1? This bug causes some mods to work on forge but not in neo

**Comment by Shadows-of-Fire** [comment]
Did forge move it in 1.20.1?  This is a nontrivial breaking change, so I would have it expected it to stay there

**Comment by KnightMiner** [comment]
Forge deprecated it and moved the place the patches call, no need to delete the method to fix this.

**Comment by pupnewfster** [comment]
And the docs of the event specify it is only fired client side. So while yes it isn’t binary breaking, it is a logical breaking change, and depending on the implementation of mods who listen to the event could cause crashes if it starts being fired server side as well. Hence why we couldn’t and didn’t pull this from upstream in 1.20.1 as it fell in the category of the breaking changes that upstream randomly decided to make post RB.

**Comment by embeddedt** [comment]
Should we just not fire the event on the server in 20.1? That's the only "non-breaking" solution but it means the behavior still differs from Forge on that version.

**Comment by KnightMiner** [comment]
Could also just fire 2 events on 1.20.1 easily enough. Would not be compatible with forge firing it on both sides, but better than not having that option at all. Someone wishing to write for both could do so with the right condition/class loading prevention.

That said, at a glance the event fires on both sides in 1.20.1. So its just wrong javadoc. I don't think its fair to call it a breaking change to make the javados consistent with what actually happens.

**Comment by embeddedt** [comment]
> I don't think its fair to call it a breaking change to make the javados consistent with what actually happens.

I know for sure we debated this a while back and I don't remember what the consensus was.

**Comment by Shadows-of-Fire** [comment]
> That said, at a glance the event fires on both sides in 1.20.1

Well no that's the thing, the vanilla path is common but only invoked on client, and the hook is in client, so invoking it from common will classload `ClientHooks` and die.

But if forge moved it we should probably just move it for sanity, so w/e

**Comment by MehVahdJukaar** [comment]
So i now have 2 mods that rely on this stuff to function and this means they cant work on Neo for 1.20.1 which is confusing for users. Back when this stuff was changed in forge i had some reports from other mods actually loading client classes from there but both of those have been adressed. To my knowledge there arent other mods that would break by having this moved (doesnt mean that there arent, just none that have been reported to me)

**Comment by embeddedt** [comment]
@MehVahdJukaar This should be fixed in the latest NeoForge build on 20.1.

**Comment by MehVahdJukaar** [comment]
awesome thanks alot!

**Pull request merged**
