### PR TITLE
Add RenderGuiLayerEvent.Pre#isGoingToRender(), allowing to determine whenever layer is actually going to render on screen

### PR DESCRIPTION
**Pull request by DBotThePony**
Additionally, adds new RegisterGuiLayersEvent API methods, allowing to specify own "rendering condition" which is visible to other mods in isGoingToRender()

Introduces no breaking changes, everything that is declared as public API is binary compatible.

From `#neoforge-github`:

> what's the usecase of having this `isGoingToRender` parameter?

> Not duplicating logic regarding whenever hud element is actually rendered
Currently, all hud elements are firing this event
Even if they render nothing
E.g. Hunger layer event is still fired if player is in creative, so mod makers have to duplicate vanilla logic in their event listener to check separately if they actually need to draw their hunger bar replacement or similar
This check differ a little from version to version, which also creates error prone situations during mod porting
And as well it all being not very intuitive at first that layer events are called even if player have pressed F1

> This PR creates middle ground, events continue to get called, so mods depending on this behavior don't get broken, while also addressing issue regarding checking if layer has actually rendered anything without duplicating logic
I have no idea why this havent been merged yet

### CODE REVIEW

**Comment by XFactHD** [comment]
Looking at the description and the changes, it's not entirely clear to me what this PR is actually trying to achieve. The description and some of the doc comments seem to suggest that the intent is to inform accurately whether a given HUD element has rendered anything. The actual code changes however do not reflect that at all as the `BooleanSupplier` would always return true for any vanilla element, regardless of whether anything was rendered or not.

**Comment by DBotThePony** [comment]
> The actual code changes however do not reflect that at all as the BooleanSupplier would always return true for any vanilla element

You didn't carefully read the code, specifically this:
https://github.com/neoforged/NeoForge/pull/1505/files#diff-d63054cd9327548079defb5ae533adb27874f2c9844c1d0abbb8077e7e0e971dR46-R54

`add` gets called by vanilla code (because `GuiLayerManager` completely replaces `LayeredDraw` through patches), with second argument having correct logic determining whenever element should be drawn

dLmOC94Ubg
iabDfMjpUO
bdyDre59R2

Unless something got changed in more recent minecraft/neoforge versions, this PR is correct.

**Comment by XFactHD** [comment]
Fair, I missed this one specific check. With that said, these three player health components are the only case where the flag is actually accurate, everything else just returns whether the entire UI is hidden by pressing F1. Or in other words, the added predicate could at best be considered a "may render" indicator which is in my opinion of questionable usefulness.

**Comment by DBotThePony** [comment]
> could at best be considered a "may render" indicator which is in my opinion of questionable usefulness.

If you are saying this should be improved further to be effective by introducing patches to related code pieces and pulling out their top "if" render condition into boolean supplier then i agree, but your reasoning/wording sounds hostile (at least to me) "why would we need this", considering the amount of time this PR is stalled by no coherent/definitive response (yes/no) from other team members despite being bought up twice in discord discussion channel.

But like i said before during discord discussion, right now event listeners are fired for situations when vanilla dont render specific hud element, but mods want to enhance/replace vanilla element, which require mods to duplicate "if" condition code into their own mods, which can lead to hard to catch bugs during porting (during course of 1.19-1.21 that condition changed at least twice in context of survival bars, once when ForgeGui didn't account for something i dont remember, and second when NeoForge removed helper method altogether, telling modders just to duplicate vanilla code) when "if" condition changes but old code continues to be valid from compiler viewpoint.

How long has it been that multiple mods which replaced health bar/armor bar/added power bar to gui suffered from rendering their own stuff when UI was hidden by F1? By player going into Creative? By having F1 *and* Esc menu open (yes, some mods properly handled F1 but magically reappeared when both F1 and Esc was pressed)?

Sure this PR will delegate this burden to Neoforge, but isn't Neoforge is meant to provide this kind of framework which takes care of such details? Considering with these changes, modders who define custom GUI layers will be able to communicate with other mods whenever their layer is being drawn?

**Comment by Technici4n** [comment]
> Sure this PR will delegate this burden to Neoforge, but isn't Neoforge is meant to provide this kind of framework which takes 
care of such details?

I am against taking on maintenance burden for that. In the past, we have tended to not notice these issues, and as a result break vanilla rendering.

If you are replacing or enhancing vanilla elements, it makes sense to me that you would be careful to keep your mod in sync with vanilla changes in that area.

> your reasoning/wording sounds hostile

If a PR author cannot convince us that a PR is useful, then we will not accept it. Nothing personal.

**Comment by DBotThePony** [comment]
After discussion in discord channel (this pr will require drastic changes in patches) and changed approach in our codebase regarding layered render events, this pr is no longer feasiable.

However, it (discussion) does not address the problem with `RenderGuiLayerEvent` being fired for all gui elements (even "parent layer" is hidden completely, which make all children layers not render anything but still fire appropriate events), which will confuse unaware modders.

**Comment by TelepathicGrunt** [comment]
can we have an issue report made for this so we don't forget about trying to improve this area of code/event? 

(Edit sorry, hit wrong button)

**Comment by DBotThePony** [comment]
The only thing you can do here is to update `RenderGuiLayerEvent` docs to clear any confusion, because fixing one issue (not firing events for not rendered gui elements/providing "going to render" boolean flag in event) will automatically solve the other, because they both rely on updating same gui patches (which have been discussed to be a no-go), so i don't think separate issue is necessary, unless you won't update docs right away.

**Pull request closed without merging**
