### PR TITLE
Add `TestHolderGenerator` annotation

### PR DESCRIPTION
**Pull request by Sirttas**
This PR add the `TestHolderGenerator` to the testframework. It's the contrepart  of the `GameTestGenerator` annotation.
ex:

```java
@TestHolderGenerator
public static List<Test> generateTests() {
    return List.of(
        ...
    );
}
```

### CODE REVIEW

**Comment by Matyrobbrt** [comment]
I'm not so keen on having this annotation as part of the framework, can't you achieve this by just registering your tests to the framework manually since you have to produce them anyway?

**Comment by Sirttas** [comment]
> I'm not so keen on having this annotation as part of the framework, can't you achieve this by just registering your tests to the framework manually since you have to produce them anyway?

Yes you can, the goal is to have something to easier move from the old system and be more consistent with it. It also make it easier to regroup tests together.

**Comment by Matyrobbrt** [comment]
I still don't see the point. If you're generating tests, you also lose all the utility annotations provided by the framework for game tests, so it's not any different from a normal game test. The test registration methods were designed for other use cases, the annotation just serves as more magic and feature duplication. `SimpleGameTestTest` is also basically a normal game test, it would provide no benefit over normal game tests.

Being in-line with vanilla is not exactly a goal of the test framework.

**Comment by Sirttas** [comment]
Ok, I thought it would make things easier to adopt the framework.

**Pull request closed without merging**
