### PR TITLE
[1.21] Make Boat.Type enum extensible

### LINKED ISSUE #491: Patch in extensible support for Boat$Type
Boats are currently 90% of the way doable in terms of modded additions without requiring a whole new entity and the like

The vast majority of this remaining gap can be resolved by making Boat.Type an extensible enum.

The only things remaining from there would be to figure out how to properly redirect the `getDropItem` methods in Boat and ChestBoat, since they're just a static enum switch

Ideally this should be done before going to stable, as people who did a big silly and made an enum switch for a boat without a default statement might be inexplicably unsafe after this change

### PR DESCRIPTION
**Pull request by XFactHD**
This PR makes the `Boat.Type` enum extensible to make it easier for mods to provide custom boats and rafts.

Fixes #491

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
So, I have two questions:

First, are we making the assumption that all boats need to have an associated chest boat, or in those instances, the user should return `Items.AIR` in the supplier?

Second, do we care about people creating their own boat variants, like a furnace boat variant, and having that stored within the enum for common access?

**Comment by XFactHD** [comment]
1. I'd say the mod supplying the given boat type should just provide air in that case. The boat item suppliers aren't accessible from the outside anyway, in large part because they are useless for vanilla boat types, and boats should realistically only be spawned by their item or the dispense behavior registered for their item.
2. I'm not sure that's useful. Making new boat variants for all boat types involves more than just creating the entity and item, you'd also need all the assets, at which point you need dedicated support for modded types anyway, so you can also just populate a lookup table of some kind, similar to how vanilla uses a switch statement for the items.

**Comment by ChampionAsh5357** [comment]
1. We may want to make sure we're doing some sanity checks then, though I can't imagine a scenario where we would run into something like that unless some general logic is happening somewhere.

2. Makes sense. It was just one of the thoughts that came to my mind since it feels like a hardcoded annoyance if vanilla decides to add more boat variants in the future.

**Comment by XFactHD** [comment]
I'm not quite sure what kind of sanity checks we could do for that

**Review by FiniteReality — DISMISSED** [review]
This seems fine to me, implementation wise. I don't think Vanilla would ever add more boat... subtypes, I suppose is the word? without a reasonably large change to this system anyway. As for boat types that don't support certain combinations of material/attachments/etc, returning air and documenting it for mods is likely the best we can do.

**Review by RaymondBlaze — COMMENTED** [review]
It would be nice if we could have some control over the dropped `Items.STICK` on breaking a boat through a `Supplier<Item>` field in the `Boat.Type`. As the test shows, a new boat type need not to be made of wood planks, and thus might not drop sticks.

**Comment by XFactHD** [comment]
Good point, I'll add an option to provide a stick item

**Review by RaymondBlaze — APPROVED** [review]

**Review by marchermans — APPROVED** [review]
I think this is a great start.
Have you considered the ability to supply your own model based on the Boat Type?

**Comment by XFactHD** [comment]
I have not looked too deep into that, but it would certainly be possible to add that. I think that's better suited for a separate PR though.

**Review by marchermans — APPROVED** [review]

**Pull request merged**
