### PR TITLE
[1.20.x] Network Capability

### PR DESCRIPTION
**Pull request by TT432**
Disclaimer: I am not a native English speaker and may have some errors in English.
---
I've been writing forge mods for a while and have been plagued by network synchronization with capability, and I want to simplify the network synchronization process with a set of APIs.

I'm not sure if my writing is conventional, so I'm only working on the `ItemStack` part for now, and I'm hoping to get some feedback to determine if I should continue with the system in the same way.

Thank you for your feedback.

### CODE REVIEW

**Comment by TelepathicGrunt** [comment]
Note, your PR might be impacted by this capability rework PR. https://github.com/neoforged/NeoForge/pull/73

If so, might be a good idea to wait until that PR is merged first before doing this one. Or ask @Technici4n if it is worth adding network sync to his PR (unless that is out of scope)

**Comment by justliliandev** [comment]
network sync was decided as out of scope for #73 as that PR is already fairly complex. ItemStack Attachments will already be moved to the stack nbt, so there is no need for additional syncing for them. Also Caps are no longer used for datastorage, so the syncing has to be moved to the Attachment System. This PR kinda only makes sense for 1.20.1, or added later as additions to the attachment system.

**Comment by Technici4n** [comment]
#73 already syncs item stack data attachments (the replacement for capability data storage).

**Comment by TT432** [comment]
Thanks a lot! I will close the PR and wait for #73.

**Pull request closed without merging**
