### PR TITLE
[1.21] Add `HolderLookup.Provider` param to `RecipeProvider#buildRecipes`

### LINKED ISSUE #1302: [1.21] Patch `HolderLookup.Provider` param to `RecipeProvider#buildRecipes`
Vanilla doesn't use their own extended recipe output system, however mods often do. Modders have to use some workaround currently to provide outputs with enchantments, for example, like statically storing the provider after it's resolved by something. This is prone to breakage. NeoForge could provide a patch in `RecipeProvider` to supply the `HolderLookup.Provider`, thereby giving a safe method to use the lookup and support Neo's own `DataComponentIngredient` for dynamic registry dependent components.

### PR DESCRIPTION
**Pull request by dhyces**
Closes #1302

> Vanilla doesn't use their own extended recipe output system, however mods often do. Modders have to use some workaround currently to provide outputs with enchantments, for example, like statically storing the provider after it's resolved by something. This is prone to breakage. NeoForge could provide a patch in RecipeProvider to supply the HolderLookup.Provider, thereby giving a safe method to use the lookup and support Neo's own DataComponentIngredient for dynamic registry dependent components.

Adds a method which accepts a `HolderLookup.Provider` for recipes which may depend on generated dynamic registry elements and defaults to the vanilla method for regular handling. Also removes the `abstract` keyword from vanilla's `RecipeProvider`, providing the option of using either of the two methods for datagen.

### CODE REVIEW

**Comment by Fuzss** [comment]
Why must this be a breaking change? Also removing the vanilla method doesn't go so well with multi-loader projects with a `RecipeProvider` in common.

Instead you could keep the vanilla `buildRecipes(RecipeOutput)` method, and implement your new method `buildRecipes(RecipeOutput,HolderLookup.Provider)` as an overload for that. `buildRecipes(RecipeOutput)` can no longer be abstract then of course, it must have an empty body.

This also avoids having to patch all the vanilla recipe providers.

**Comment by dhyces** [comment]
> Instead you could keep the vanilla `buildRecipes(RecipeOutput)` method, and implement your new method `buildRecipes(RecipeOutput,HolderLookup.Provider)` as an overload for that. 

Yes, this is exactly what I mentioned in the description.

> `buildRecipes(RecipeOutput)` can no longer be abstract then of course, it must have an empty body.

Not sure that I like making `buildRecipes` a default method however, but that's an option

**Comment by ChampionAsh5357** [comment]
Is there a reason why this couldn't be done with a protected field and a new constructor similar to the tags provider? Also, what is the reason for adding this to NeoForge in general? A revenant usecase would be helpful to understand why this should be available to all modders rather than just yourself by subclassing the recipe provider.

**Comment by dhyces** [comment]
> Also, what is the reason for adding this to NeoForge in general? A revenant usecase would be helpful to understand why this should be available to all modders rather than just yourself by subclassing the recipe provider.

I've just copied the description contents of the relevant issue into this PR for visibility. The relevant use case can now be found in this PR's description, copied here again for convenience:
> Vanilla doesn't use their own extended recipe output system, however mods often do. Modders have to use some workaround currently to provide outputs with enchantments, for example, like statically storing the provider after it's resolved by something. This is prone to breakage. NeoForge could provide a patch in RecipeProvider to supply the HolderLookup.Provider, thereby giving a safe method to use the lookup and support Neo's own DataComponentIngredient for dynamic registry dependent components.

> Is there a reason why this couldn't be done with a protected field and a new constructor similar to the tags provider? 

I do not see how that could be reasonably accomplished without annoyance. The lookup is within a future and cannot be safely resolved to pass it into a `RecipeProvider`. I will however update this PR to reflect the alternate option as it seems people would rather have that instead of breakages. It would however diminish visibility of the relevant consumer-facing methods, but it should be easy enough for users to determine which methods should be overridden for datagen.

**Comment by Fuzss** [comment]
Marking the vanilla method as `@Deprecated` could help. Adding `HolderLookup.Provider` is reasonable, just making it a breaking change is not necessary imo.

**Comment by dhyces** [comment]
> Marking the vanilla method as `@Deprecated` could help. Adding `HolderLookup.Provider` is reasonable, just making it a breaking change is not necessary imo.

I don't think it needs to be marked as deprecated either really. It's perfectly fine to use, the other method just allows more functionality that is otherwise difficult to achieve. I do agree that making it a breaking change is annoying, though I do see it as the best route for visibility.

**Review by robotgryphon — APPROVED** [review]

**Review by ApexModder — APPROVED** [review]

**Pull request merged**
