### PR TITLE
[1.20.4] Split mod logo filepath on slashes for mod list menu

### LINKED ISSUE #347: Crash when clicking on an entry in the mod menu if the mod has a logo path with slashes
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.5-beta

**Logs:** [Link](https://gist.github.com/bluebear94/ec51ee0f4f25efbec7d745c9d2350ba2) with [Caxton 0.5.2+1.20.4-NEOFORGE](https://modrinth.com/mod/caxton/version/0.5.2+1.20.4-NEOFORGE) as the offending mod

**Steps to Reproduce:**
 1. In `mods.toml`, set `logoFile` to a path with slashes under the mod metadata
 2. Start the game
 3. Open the mod menu
 4. Click on the entry for the offending mod

**Description of issue:** When clicking on an entry in the mod menu, the game crashes if the mod in question has a logo path that contains slashes.

This happens because `ModListScreen` passes in a single string to `PathPackResources#getRootResource` without splitting the path into its constituent elements.

### PR DESCRIPTION
**Pull request by TelepathicGrunt**
Resolves: https://github.com/neoforged/NeoForge/issues/347

I did both / and \ just in case someone tries either slash. In the end, the slashes will be ignored and handled properly by MC with this PR

### CODE REVIEW

**Comment by XFactHD** [comment]
This isn't the correct solution to this issue. `PackResources#getRootResource()` takes a vararg to allow passing in multiple distinct file names in order to get the first one of them that's available. Root resource in this case specifically refers to a file in the root of the pack (i.e. like the `pack.mcmeta` and `pack.png`, which are the two things vanilla uses this method for). The proposed solution would cause the pack to search for each part of the path as a file in the pack root and return null since none of them exist.

With the current implementation, specifying a non-root path for the logo is user error. The MDK's mods.toml specifically specifies that this is a file name for an image in the root of the JAR: https://github.com/neoforged/MDK/blob/main/src/main/resources/META-INF/mods.toml#L27.

Whether we should allow non-root paths for the logo is a decision I'll leave up to others.

**Comment by TelepathicGrunt** [comment]
I would strongly recommend allowing non-root images. I put my images in the asset folder where it should be as images are an asset and where users would expect an image asset to be in a resource pack.
image

In fact, this was working in Forge afaik as I tested this foldering there a while ago before publishing my mod. But now it seems NeoForge crashes my mod so it's a regression in behavior.

Just checked, 1.20.1 Forge does not crash my mod for my pathing I use.
image
image

**Comment by TelepathicGrunt** [comment]
> This isn't the correct solution to this issue. `PackResources#getRootResource()` takes a vararg to allow passing in multiple distinct file names in order to get the first one of them that's available. Root resource in this case specifically refers to a file in the root of the pack (i.e. like the `pack.mcmeta` and `pack.png`, which are the two things vanilla uses this method for). The proposed solution would cause the pack to search for each part of the path as a file in the pack root and return null since none of them exist.
> 
> With the current implementation, specifying a non-root path for the logo is user error. The MDK's mods.toml specifically specifies that this is a file name for an image in the root of the JAR: https://github.com/neoforged/MDK/blob/main/src/main/resources/META-INF/mods.toml#L27.
> 
> Whether we should allow non-root paths for the logo is a decision I'll leave up to others.

That's not the behavior I am seeing with regards to PathPackReosurces$getRootResource. It takes the vararg of strings and then passes them to FileUtil.resolvePath.
image

Then in resolvePath, it will go into default block for 2 or more strings where it then stuffs the list entries into an array minus the file name part itself. Then it feeds that entire path array and file name to getPath to construct the path to look for the file at.
image

This does work in my testing as it properly finds the image under `assets/neoforge/neoforged_logo.png` when that is where image is and mods.toml has that entry.

**Review by XFactHD — APPROVED** [review]
Apparently I can't read, the solution is in fact correct and my analysis of `VanillaPackResources` was entirely wrong

**Review by embeddedt — APPROVED** [review]

**Pull request merged**
