### PR TITLE
[1.20.4] Add `onDestroyedByPushReaction` hook

### PR DESCRIPTION
**Pull request by Spinoscythe**
Straight port of #142.

### CODE REVIEW

**Comment by Lordfirespeed** [comment]
Thankyou for picking this up from me!

**Comment by Spinoscythe** [comment]
Will probably do tests today

**Comment by Lordfirespeed** [comment]
> Will probably do tests today

I've actually just opened a PR for some tests on your repo - if it turns out we came up with different ones, the more tests the better!

**Comment by Spinoscythe** [comment]
> > Will probably do tests today
> 
> I've actually just opened a PR for some tests on your repo - if it turns out we came up with different ones, the more tests the better!

do you mind linking the tests here?

**Comment by Lordfirespeed** [comment]
> do you mind linking the tests here?

Not at all - [Here](https://github.com/Nekretaur/NeoForge/pull/2)

**Comment by Lordfirespeed** [comment]
License violation - looks like I forgot to add a copyright/license header to the test file!

**Comment by Spinoscythe** [comment]
> License violation - looks like I forgot to add a copyright/license header to the test file!

fixed it, dw

**Comment by Shadows-of-Fire** [comment]
Where did all the unrelated javadoc formatting changes come from?

**Comment by Lordfirespeed** [comment]
> Where did all the unrelated javadoc formatting changes come from?

Great question ... it could have been an overzealous IDE on my part.

**Comment by Spinoscythe** [comment]
@Shadows-of-Fire fixed!

**Review by marchermans — APPROVED** [review]

**Pull request merged**
