### PR TITLE
Remove some missed deprecations

### PR DESCRIPTION
**Pull request by ZestyBlaze**
Some of the deprecations were missed in the port to 1.21.2(.3), the two I have removed are `#c:slimeballs` in favour of the new `#c:slime_balls` and the old `DeferredRegister.createDataComponents(String)` initalizer as we have the new much more favourable method. Both of these are things that *were* marked to be removed in 1.21.2 and were not.
I did ask about things to remove and another developer mentioned the other `createDataComponents` as it would make better sense for us to get it out as it was only used for a short period of time and the alternate option is a much better option.
I also previously looked at removing the fallbacks for the Oxidising and Waxing datamaps which *are* marked to be removed in 1.21.2 but have not been, however another maintainer said to leave them until 1.22
Another possible removal could be `IEntityExtension.serializeNBT` as this is marked to be removed too and hasn't yet as it doesn't specify a removal period

### CODE REVIEW

**Review by sciwhiz12 — CHANGES_REQUESTED** [review]
Looks fine, though you need to run the `runData` task and commit the changes.

**Comment by Matyrobbrt** [comment]
@neoforged/bots run :neoforge:runData

**Comment by Matyrobbrt** [comment]
@neoforged/bots run :neoforge:runData

**Comment by Matyrobbrt** [comment]
@neoforged/bots run :neoforge:runData

**Comment by Matyrobbrt** [comment]
@neoforged/bots run :neoforge:runData

**Comment by ZestyBlaze** [comment]
I think Matty made the bot do that for me maybe? @sciwhiz12

**Comment by Matyrobbrt** [comment]
Unfortunately, I fought the bot and it won. You'll still have to run it manually locally to delete the not needed generated files.

**Comment by ZestyBlaze** [comment]
I ran the data and that's the only file that needed deleting still apparently? So I hope that's everything and github will be happy with that

**Review by sciwhiz12 — APPROVED** [review]

**Pull request merged**
